import type { FavouritePlayer } from "./types";

/** Kareler bu klasörde bekliyor; şimdilik hepsi boş — küratör dolduracak. */
const BASE = "/assets/players/arda-turan";

/**
 * ⚠️ SAYILAR DOĞRULANMADI — dış bir kaynakla karşılaştırılmadı.
 * Küratör düzeltmesi bu dosyada tek satır.
 *
 * Bu kayıtta bilerek EKSİK bırakılan yerler var: kariyer duraklarının maç ve
 * gol sayıları `null`, çünkü güvenilir bir toplam elde yoktu. Uydurma bir
 * rakam yazmaktansa satır boş bırakıldı; küratör dolduracak.
 */
export const ardaTuran: FavouritePlayer = {
  slug: "arda-turan",
  name: "Arda Turan",
  firstName: "ARDA",
  lastName: "TURAN",
  shirt: null,
  position: "Ofansif orta saha",
  club: "Galatasaray",
  clubShort: "GS",
  country: "Türkiye",
  countryCode: "TR",
  birthDate: "30 Ocak 1987",
  birthPlace: "Bayrampaşa, İstanbul",
  height: "177 cm",
  weight: "—",
  tagline: "Topu istediği an takımın yönü değişirdi.",
  quote:
    "Kalabalığın içine top isteyen adamdı; herkesin kaçtığı yerde o dönerdi.",
  closingQuote:
    "Gitti, kazandı, döndü. Bu şehirde asıl zor olan üçüncüsüdür.",
  palette: {
    ink: "#130b09",
    accent: "#e51f2b",
    warm: "#eab04a",
    glow: "rgba(229, 31, 43, 0.32)",
    neon: "#ff7a3d",
  },
  hero: {
    id: "hero",
    src: `${BASE}/hero.jpg`,
    alt: "Arda Turan, Galatasaray forması",
    placeholder: true,
    hint: "Dikey kadraj · GS forması · topa dönük omuz · yüz net · tercihen hareket anı",
    width: 1200,
    height: 1600,
  },
  card: {
    id: "card",
    src: `${BASE}/kart.jpg`,
    alt: "Arda Turan",
    placeholder: true,
    hint: "Hub şeridindeki kart için · dikey · üst gövde · sakin bakış",
    width: 900,
    height: 1200,
  },
  badges: ["Ofansif orta saha", "Galatasaray", "Türkiye"],
  vitals: [
    { label: "Doğum tarihi", value: "30.01.1987" },
    { label: "Uyruk", value: "Türkiye" },
    { label: "Mevki", value: "Ofansif orta saha" },
    { label: "Boy", value: "177 cm" },
  ],
  storyTitle: ["Florya'dan", "Madrid'e"],
  storyLede:
    "Altyapıdan çıkıp kaptan oldu, İspanya'da iki büyük kulübün formasını giydi ve geri döndü. Bu sayfa gidişin değil, dönüşün sayfası.",
  story: [
    "Galatasaray altyapısından çıkan bir çocuk için ilk sınav yetenek değildir, dayanıklılıktır. Florya'dan A takıma yükselen listenin çoğu orada kalır. O kaldı ve 2005-06 sezonunda profesyonel hayatı başladı; yirmili yaşlarının başında pazubent koluna geçmişti bile.",
    "İlk dönemi 2011 yazında bitti. Atlético Madrid'e gitti ve İspanya'da bir Türk oyuncunun taşıyabileceğinden fazlasını taşıdı: Avrupa Ligi, ardından İspanya ligi, ardından bir Devler Ligi finali. Simeone'nin takımında koşmayan oyuncuya yer yoktur; o takımda dört yıl kaldı.",
    "2015'te Barcelona'ya geçti. Dünyanın en iyi hücum hattının yanında oynamak, top dokunma sayısını düşürmeyi kabul etmek demektir — bunu yapabilen oyuncu azdır. Sonra Türkiye'ye döndü ve Başakşehir'in ilk şampiyonluğunda kadrodaydı.",
    "2020'de sarı-kırmızıyı yeniden giydi. Otuzunu geçmiş bir on numaranın dönüşü genelde bir veda turudur; burada öyle olmadı. Kısa süre sonra futbolu bıraktı ve bu defterde kalan şey rakam değil, bir oyun biçimi: topu baskının içinde isteyen, ilk dokunuşuyla sahayı çeviren adam.",
  ],
  stats: {
    club: {
      key: "galatasaray",
      label: "Galatasaray",
      crest: {
        id: "crest-gs",
        src: `${BASE}/arma-gs.png`,
        alt: "Galatasaray arması",
        placeholder: true,
        hint: "Arma · kare ya da dikey · zemini temiz · şeffaf PNG tercih edilir",
        width: 800,
        height: 800,
      },
      entries: [
        { key: "spells", label: "Dönem", value: "2" },
        { key: "debut", label: "İlk sezon", value: "2005-06" },
        { key: "titles", label: "Süper Lig", value: "2" },
      ],
      note: "Altyapıdan çıktı, kaptan oldu, gitti ve geri döndü.",
    },
    all: {
      label: "Tüm zamanlar",
      entries: [
        { key: "superlig", label: "Süper Lig", value: "3" },
        { key: "avrupaligi", label: "Avrupa Ligi", value: "1" },
        { key: "final", label: "Devler Ligi finali", value: "2014" },
      ],
      note: "Maç ve gol toplamları bilerek boş: güvenilir bir kaynakla doğrulanmadı.",
    },
  },
  career: [
    {
      id: "galatasaray-ilk",
      years: "2005 — 2011",
      club: "Galatasaray",
      country: "Türkiye",
      note: "Altyapıdan çıktı ve daha yirmili yaşların başında pazubendi taktı.",
      tone: "#e0a832",
      matches: null,
      goals: null,
      image: {
        id: "career-galatasaray",
        src: `${BASE}/kariyer-galatasaray.jpg`,
        alt: "Arda Turan, Galatasaray formasıyla",
        placeholder: true,
        hint: "İlk dönem · GS forması · yatay · genç yüz görünsün",
        width: 1200,
        height: 800,
      },
    },
    {
      id: "atletico",
      years: "2011 — 2015",
      club: "Atlético Madrid",
      country: "İspanya",
      note: "Koşmayanın oynamadığı bir takımda dört yıl kaldı.",
      tone: "#b0262f",
      matches: null,
      goals: null,
      image: {
        id: "career-atletico",
        src: `${BASE}/kariyer-atletico.jpg`,
        alt: "Arda Turan, Atlético Madrid formasıyla",
        placeholder: true,
        hint: "Kırmızı-beyaz çubuklu forma · aksiyon karesi · yatay",
        width: 1200,
        height: 800,
      },
    },
    {
      id: "barcelona",
      years: "2015 — 2018",
      club: "Barcelona",
      country: "İspanya",
      note: "Dünyanın en iyi hücum hattının yanında az dokunmayı kabul etti.",
      tone: "#7c1f33",
      matches: null,
      goals: null,
      image: {
        id: "career-barcelona",
        src: `${BASE}/kariyer-barcelona.jpg`,
        alt: "Arda Turan, Barcelona formasıyla",
        placeholder: true,
        hint: "Camp Nou · yatay · kadraj bordo tarafı öne çıkarsın",
        width: 1200,
        height: 800,
      },
    },
    {
      id: "basaksehir",
      years: "2018 — 2020",
      club: "İstanbul Başakşehir",
      country: "Türkiye",
      note: "Bir kulübün tarihindeki ilk şampiyonluğun kadrosunda vardı.",
      tone: "#c2651c",
      matches: null,
      goals: null,
      image: {
        id: "career-basaksehir",
        src: `${BASE}/kariyer-basaksehir.jpg`,
        alt: "Arda Turan, İstanbul Başakşehir formasıyla",
        placeholder: true,
        hint: "Turuncu forma · yatay · şampiyonluk sezonundan bir kare",
        width: 1200,
        height: 800,
      },
    },
    {
      id: "galatasaray-donus",
      years: "2020 — 2021",
      club: "Galatasaray",
      country: "Türkiye",
      note: "Dönüş. Veda turu değil, kapanış cümlesi.",
      tone: "#f2c531",
      matches: null,
      goals: null,
      current: true,
      image: {
        id: "career-galatasaray-donus",
        src: `${BASE}/kariyer-galatasaray-donus.jpg`,
        alt: "Arda Turan, dönüşünde Galatasaray formasıyla",
        placeholder: true,
        hint: "Dönüş dönemi · GS forması · yatay · şeridin en güçlü karesi burası",
        width: 1200,
        height: 800,
      },
    },
  ],
  nights: [
    {
      year: 2008,
      title: "Kupanın kalktığı akşam",
      meta: "Süper Lig · 2007-08 · Galatasaray",
      line: "Sezon bittiğinde kupa Florya'ya gitti. Sahanın ortasında top isteyen adam yirmi bir yaşındaydı ve kimse ona genç muamelesi yapmıyordu.",
      image: {
        id: "night-2008-lig",
        src: `${BASE}/gece-2008-lig.jpg`,
        alt: "",
        placeholder: true,
        hint: "Şampiyonluk kutlaması · GS forması · yatay · tribün görünsün",
        width: 1200,
        height: 800,
      },
    },
    {
      year: 2008,
      title: "İki farkla geride",
      meta: "EURO 2008 · Türkiye — Çekya",
      line: "Türkiye iki farkla geriydi ve maçın son çeyreğinde skor tabelası kırıldı. O akşamı hatırlayan herkes, ilk golün kimden geldiğini de hatırlıyor.",
      image: {
        id: "night-cekya",
        src: `${BASE}/gece-cekya.jpg`,
        alt: "",
        placeholder: true,
        hint: "Milli forma · gol sevinci · yatay · 2008 dönemi",
        width: 1200,
        height: 800,
      },
    },
    {
      year: 2012,
      title: "Bükreş",
      meta: "Avrupa Ligi finali · Atlético Madrid — Athletic Bilbao",
      line: "Avrupa kupası bir Türk oyuncunun eline geçiyor. Kutlamanın en sessiz karesi, kupanın kalkmasından önce sahanın ortasında duran o an.",
      image: {
        id: "night-bukres",
        src: `${BASE}/gece-bukres.jpg`,
        alt: "",
        placeholder: true,
        hint: "Avrupa Ligi kupası · Atlético forması · yatay",
        width: 1200,
        height: 800,
      },
    },
    {
      year: 2014,
      title: "Camp Nou'da bir puan",
      meta: "La Liga · Barcelona — Atlético Madrid",
      line: "Şampiyonluk için bir beraberlik yetiyordu ve rakibin evinde alındı. İspanya'da bir ligin en zor kazanıldığı sezonun son dakikalarıydı.",
      image: {
        id: "night-campnou",
        src: `${BASE}/gece-campnou.jpg`,
        alt: "",
        placeholder: true,
        hint: "Camp Nou · Atlético forması · şampiyonluk anı · yatay",
        width: 1200,
        height: 800,
      },
    },
  ],
  personal: [
    {
      label: "Alışkanlık",
      title: "Baskının içinde top istemek",
      body: "Rakip üstüne gelirken topu isterdi; herkesin geri pas aradığı anda o dönerdi. İlk dokunuşta omzunu çevirir, savunmacıyı arkasında bırakırdı. Bu bir teknik değil, bir karar — ve o kararı saniyede verirdi.",
    },
    {
      label: "Ritim",
      title: "Yürüyüşten koşuya",
      body: "Sahada çoğu zaman yürür gibi dururdu. Sonra üç adımda iki adam geçerdi. Onu izlerken asıl bakılacak yer top değil, patlamadan önceki o iki saniyeydi.",
    },
    {
      label: "Detay",
      title: "Sol ayağın içi",
      body: "Sol ayağının içiyle vurduğu top hep aynı yörüngeyi çizerdi: yükselir, sonra son anda düşer. Ceza sahasının dışından attığı ortalarda kalecinin çıkamadığı boşluk hep aynı boşluktu.",
    },
  ],
  gallery: [
    {
      id: "gallery-1",
      src: `${BASE}/galeri-1.jpg`,
      alt: "Arda Turan",
      placeholder: true,
      hint: "Ana galeri karesi · geniş · en yüksek çözünürlük · GS forması",
      width: 1600,
      height: 900,
      caption: "Ana kare",
    },
    {
      id: "gallery-2",
      src: `${BASE}/galeri-2.jpg`,
      alt: "Maç anı",
      placeholder: true,
      hint: "Maç anı · topla buluşma · yatay",
      width: 1200,
      height: 800,
      caption: "Maç anı",
    },
    {
      id: "gallery-3",
      src: `${BASE}/galeri-3.jpg`,
      alt: "Portre",
      placeholder: true,
      hint: "Portre · dikey · yakın kadraj",
      width: 900,
      height: 1200,
      caption: "Portre",
    },
    {
      id: "gallery-4",
      src: `${BASE}/galeri-4.jpg`,
      alt: "Kaptanlık",
      placeholder: true,
      hint: "Pazubent görünen kare · dikey ya da kare",
      width: 1000,
      height: 1000,
      caption: "Pazubent",
    },
    {
      id: "gallery-5",
      src: `${BASE}/galeri-5.jpg`,
      alt: "Milli forma",
      placeholder: true,
      hint: "Milli takım forması · yatay · tercihen 2008 dönemi",
      width: 1200,
      height: 800,
      caption: "Milli forma",
    },
    {
      id: "gallery-6",
      src: `${BASE}/galeri-6.jpg`,
      alt: "Taraftarla an",
      placeholder: true,
      hint: "Tribün / taraftar · yatay · alkış ya da selam anı",
      width: 1200,
      height: 800,
      caption: "Tribün",
    },
    {
      id: "gallery-7",
      src: `${BASE}/galeri-7.jpg`,
      alt: "Kupa",
      placeholder: true,
      hint: "Kupa · şampiyonluk gecesi · dikey",
      width: 900,
      height: 1200,
      caption: "Kupa",
    },
  ],

  /**
   * SPLIT hero + ARC imza: solda tipografi bloğu, sağda portre ve arkada
   * yörünge yayı — sol ayağın çizdiği eğri. Anton'un poster kapitali bayrak
   * kırmızısıyla, halo dokusu da altın ışıkla çalışıyor.
   */
  design: {
    voice: "poster",
    hero: "split",
    signature: "arc",
    rhythm: "open",
    texture: "halo",
  },
};
