import type { FavouritePlayer } from "./types";

/** Küratörün yükleyeceği kareler bu klasörde bekleyecek. */
const BASE = "/assets/players/baris-alper";

/**
 * ⚠️ SAYILAR DOĞRULANMADI — dış bir kaynakla karşılaştırılmadı.
 * Küratör düzeltmesi bu dosyada tek satır.
 *
 * Bu kayıtta bilerek YAZILMAYAN sayılar var: maç, gol, asist toplamları,
 * forma numarası, doğum günü, boy ve kilo. Emin olunmadığı için satır hiç
 * konmadı; uydurma bir rakam yazmaktansa boş bırakmak tercih edildi.
 * Küratör bildiği değeri yazdığında satır kendiliğinden dolar.
 */
export const barisAlperYilmaz: FavouritePlayer = {
  slug: "baris-alper",
  name: "Barış Alper Yılmaz",
  firstName: "BARIŞ ALPER",
  lastName: "YILMAZ",
  shirt: null,
  position: "Kanat",
  club: "Galatasaray",
  clubShort: "GS",
  country: "Türkiye",
  countryCode: "TR",
  birthDate: "2000",
  birthPlace: "Ankara, Türkiye",
  height: "—",
  weight: "—",
  tagline: "Topu kaybettiği saniyede geri koşmaya başlayan kanat.",
  quote:
    "Alt ligden gelen bir çocuğun doksan dakika boyunca yorulmayı reddetmesi.",
  closingQuote:
    "Ankara'nın amatör sahalarından buraya kadar; yolu kısaltan tek şey koşmaktı.",
  palette: {
    ink: "#100a08",
    accent: "#ffa62b",
    warm: "#d13a20",
    glow: "rgba(255, 166, 43, 0.30)",
    neon: "#ff5a1f",
  },
  hero: {
    id: "hero",
    src: `${BASE}/hero.jpg`,
    alt: "Barış Alper Yılmaz, Galatasaray forması",
    placeholder: true,
    hint: "Dikey kadraj · GS forması · koşu hâlinde · gövde eğik, saç ve forma savrulsun · yüz net",
    width: 1200,
    height: 1600,
  },
  card: {
    id: "card",
    src: `${BASE}/kart.jpg`,
    alt: "Barış Alper Yılmaz",
    placeholder: true,
    hint: "Hub şeridindeki kart · dikey · üst gövde · sakin bakış, sert ışık",
    width: 900,
    height: 1200,
  },
  badges: ["Kanat", "Galatasaray", "A Millî Takım"],
  vitals: [
    { label: "Doğum yeri", value: "Ankara" },
    { label: "Doğum yılı", value: "2000" },
    { label: "Uyruk", value: "Türkiye" },
    { label: "Mevki", value: "Kanat / forvet" },
  ],
  storyTitle: ["Alt liglerden", "millî formaya"],
  storyLede:
    "Ankara'nın kimsenin bakmadığı sahalarından Galatasaray'ın kanadına ve millî takıma: yol boyunca değişmeyen tek şey koşu miktarıydı.",
  story: [
    "Ankara'da başladı ve uzun süre kimsenin bakmadığı sahalarda oynadı. Alt lig futbolunun televizyonu yoktur; çoğu zaman tribünü de, kaydı da yoktur. Oradan çıkan bir oyuncunun ilk sermayesi yetenek değil dayanıklılıktır.",
    "2021 yazında Galatasaray'a geldiğinde adı geniş kitlelerce bilinmiyordu. İlk aylarda mevkisi bile net değildi: bazen sağ kanat, bazen sol, bazen forvetin yanı. Bir oyuncuyu her yere koyabiliyorsanız ya çok yönlüdür ya da yeri yoktur; onunki birincisi çıktı.",
    "Onu tribünde tutan şey ilk gün de bugün de aynı: koşusu. Topu kaybettiğinde durup hakeme bakan kanat oyuncusu çoktur; o, kaybettiği saniyede geri dönmeye başlar. Bu tür bir çabanın istatistiği yoktur ama stadyumdaki herkes görür.",
    "Sonra şampiyonluklar geldi, millî forma geldi, Avrupa geceleri geldi. Ankara'nın amatör sahalarından çıkıp bir Avrupa turnuvasında Türkiye'nin kanadında koşmak düz bir kariyer çizgisi değil, sıçramadır. Sıçrayanlar genelde ilk yılda yorulur; o yorulmadı.",
  ],
  stats: {
    club: {
      key: "galatasaray",
      label: "Galatasaray",
      crest: {
        id: "crest-gs",
        src: `${BASE}/arma-gs.png`,
        alt: "Galatasaray arması",
        placeholder: true,
        hint: "Galatasaray arması · kare ya da dikey · zemin temiz, kenarlar keskin",
        width: 512,
        height: 512,
      },
      entries: [
        { key: "since", label: "Geliş", value: "2021" },
        { key: "firstSeason", label: "İlk sezon", value: "2021-22" },
        { key: "titles", label: "Süper Lig", value: "3" },
      ],
      note: "Üst üste üç Süper Lig (2022-23, 2023-24, 2024-25). Maç ve gol toplamları doğrulanmadığı için bu deftere yazılmadı.",
    },
    all: {
      label: "Tüm zamanlar",
      entries: [
        { key: "national", label: "Millî takım", value: "A Millî" },
        { key: "tournament", label: "Turnuva", value: "EURO 2024" },
        { key: "titles", label: "Süper Lig", value: "3" },
      ],
      note: "Kariyer maç, gol ve asist toplamları küratör doğrulamasını bekliyor — uydurma sayı yazılmadı.",
    },
  },
  career: [
    {
      id: "amator",
      years: "2010'ların sonu",
      club: "Ankara · amatör yıllar",
      country: "Türkiye",
      note: "Adı hiçbir listede geçmiyordu; koşulan mesafe dışında sermayesi yoktu.",
      tone: "#5f584b",
      matches: null,
      goals: null,
      image: {
        id: "career-amator",
        src: `${BASE}/kariyer-amator.jpg`,
        alt: "Barış Alper Yılmaz, amatör yıllar",
        placeholder: true,
        hint: "Arşiv karesi · amatör / alt lig sahası · gençlik fotoğrafı · net kare bulunamazsa yuva boş kalabilir",
        width: 1200,
        height: 675,
      },
    },
    {
      id: "ankara-demirspor",
      years: "2021 öncesi",
      club: "Ankara Demirspor",
      country: "Türkiye",
      note: "Alt ligde profesyonellik: az seyirci, çok yol, dar saha.",
      tone: "#8d8778",
      matches: null,
      goals: null,
      image: {
        id: "career-ankara-demirspor",
        src: `${BASE}/kariyer-ankara-demirspor.jpg`,
        alt: "Barış Alper Yılmaz, Ankara Demirspor formasıyla",
        placeholder: true,
        hint: "Alt lig maçı · yatay · boş tribün görünürse tam isabet",
        width: 1200,
        height: 675,
      },
    },
    {
      id: "galatasaray",
      years: "2021 —",
      club: "Galatasaray",
      country: "Türkiye",
      note: "Bilinmeyen bir isimden takımın ciğerine dönüşme.",
      tone: "#ffa62b",
      matches: null,
      goals: null,
      current: true,
      image: {
        id: "career-galatasaray",
        src: `${BASE}/kariyer-galatasaray.jpg`,
        alt: "Barış Alper Yılmaz, Galatasaray formasıyla",
        placeholder: true,
        hint: "GS forması · tam hız koşu ya da gol sevinci — şeridin en güçlü karesi burası",
        width: 1200,
        height: 675,
      },
    },
  ],
  nights: [
    {
      year: 2021,
      title: "İlk sezon",
      meta: "Süper Lig · Galatasaray'a geliş",
      line: "Alt ligden gelen bir oyuncunun ilk kez on binlerce kişinin önünde ısınması. O akşam tribünde adını doğru dürüst bilen azdı.",
      image: {
        id: "night-ilk-sezon",
        src: `${BASE}/gece-ilk-sezon.jpg`,
        alt: "",
        placeholder: true,
        hint: "İlk sezon · GS forması · ısınma ya da oyuna giriş anı · yatay",
        width: 1200,
        height: 800,
      },
    },
    {
      year: 2023,
      title: "İlk şampiyonluk",
      meta: "Süper Lig · 2022-23",
      line: "Geldikten iki yıl sonra ilk kupa. Alt lig sahalarıyla o gecenin arasındaki mesafe iki yıldan çok daha uzundu.",
      image: {
        id: "night-ilk-sampiyonluk",
        src: `${BASE}/gece-ilk-sampiyonluk.jpg`,
        alt: "",
        placeholder: true,
        hint: "Şampiyonluk gecesi · konfeti / kupa · yüz net · yatay",
        width: 1200,
        height: 800,
      },
    },
    {
      year: 2024,
      title: "Millî formayla turnuva",
      meta: "EURO 2024 · Almanya · Türkiye",
      line: "Türkiye turnuvada yol alırken kanadı doksan dakika boyunca tek başına tutan oydu. En çok konuşulan isim değildi; en az duran isimdi.",
      image: {
        id: "night-euro",
        src: `${BASE}/gece-euro.jpg`,
        alt: "",
        placeholder: true,
        hint: "Millî takım forması · koşu ya da ikili mücadele · yatay",
        width: 1200,
        height: 800,
      },
    },
    {
      year: 2025,
      title: "Üst üste üçüncü",
      meta: "Süper Lig · 2024-25",
      line: "Üç sezon üst üste. Geldiği yıl kadronun en bilinmeyen ismiyken, üçüncü kupada takımın üzerine kurulduğu isimlerden biriydi.",
      image: {
        id: "night-ucuncu-kupa",
        src: `${BASE}/gece-ucuncu-kupa.jpg`,
        alt: "",
        placeholder: true,
        hint: "Kupa gecesi · takım halinde ya da tek kadraj · sarı-kırmızı ışık · yatay",
        width: 1200,
        height: 800,
      },
    },
  ],
  personal: [
    {
      label: "Koşu",
      title: "Geri dönüş",
      body: "Topu kaybettiği saniyede geri koşmaya başlar. Kanat oyuncularının çoğu bir an durur: itiraz eder, ellerini açar, sonra döner. O ara saniyeyi hiç kullanmıyor — arşivdeki en sevdiğim alışkanlığı bu.",
    },
    {
      label: "Vücut",
      title: "Omuz",
      body: "Topu ayağıyla değil omzuyla koruyor. Rakibi yanına aldığında düşmüyor, dengesini bozdurmuyor; faul aramak yerine ayakta kalmayı seçiyor. Bu ligde bunu seçen kanat sayısı az.",
    },
    {
      label: "Dürüstlük",
      title: "Ham taraf",
      body: "Son vuruşu her zaman koşusu kadar temiz değil ve bunu saklamaya gerek yok. Ama aynı ham taraf, ceza sahasına girerken düşünmemesini de sağlıyor. En çok eleştirildiği yerle en çok işe yaradığı yer aynı yer.",
    },
  ],
  gallery: [
    {
      id: "gallery-1",
      src: `${BASE}/galeri-1.jpg`,
      alt: "Barış Alper Yılmaz",
      placeholder: true,
      hint: "Ana galeri karesi · geniş · en yüksek çözünürlük · tam hız koşu",
      width: 1600,
      height: 900,
      caption: "Ana kare",
    },
    {
      id: "gallery-2",
      src: `${BASE}/galeri-2.jpg`,
      alt: "Maç anı",
      placeholder: true,
      hint: "İkili mücadele · omuz omuza · yatay",
      width: 1200,
      height: 800,
      caption: "Mücadele",
    },
    {
      id: "gallery-3",
      src: `${BASE}/galeri-3.jpg`,
      alt: "Portre",
      placeholder: true,
      hint: "Portre · dikey · ter ve nefes görünsün · sert tek kaynak ışık",
      width: 900,
      height: 1200,
      caption: "Portre",
    },
    {
      id: "gallery-4",
      src: `${BASE}/galeri-4.jpg`,
      alt: "Gol sevinci",
      placeholder: true,
      hint: "Gol sevinci · dikey · kollar açık, tribüne doğru koşu",
      width: 900,
      height: 1200,
      caption: "Sevinç",
    },
    {
      id: "gallery-5",
      src: `${BASE}/galeri-5.jpg`,
      alt: "Millî forma",
      placeholder: true,
      hint: "A Millî Takım forması · yatay · ay-yıldız görünsün",
      width: 1200,
      height: 800,
      caption: "Millî forma",
    },
    {
      id: "gallery-6",
      src: `${BASE}/galeri-6.jpg`,
      alt: "Antrenman",
      placeholder: true,
      hint: "Antrenman · yatay ya da kare · sabah ışığı, çamurlu saha",
      width: 1200,
      height: 900,
      caption: "Antrenman",
    },
    {
      id: "gallery-7",
      src: `${BASE}/galeri-7.jpg`,
      alt: "Tribün",
      placeholder: true,
      hint: "Taraftarla an · kupa ya da tribün önü · dikey",
      width: 900,
      height: 1200,
      caption: "Tribün",
    },
  ],

  /**
   * Barış Alper'in imzası TEMPO: Bebas kondansesi skorboard sesiyle konuşuyor,
   * hero portreyi kadrajdan yararak çıkarıyor, çapraz bant kesip geçiyor.
   * Sıkışık ritim ve film graini nefes bırakmıyor — sayfanın kendisi koşuyor.
   */
  design: {
    voice: "condensed",
    hero: "kinetic",
    signature: "sash",
    rhythm: "tight",
    texture: "grain",
  },
};
