import type { FavouritePlayer } from "./types";

/** Kareler bu klasörde bekliyor; hepsi küratör modundan yüklenecek. */
const BASE = "/assets/players/burak-yilmaz";

/**
 * ⚠️ SAYILAR DOĞRULANMADI — dış bir kaynakla karşılaştırılmadı.
 * Küratör düzeltmesi bu dosyada tek satır.
 *
 * Bu kayıtta bilerek EKSİK bırakılan şeyler var: forma numarası, kilo, kulüp
 * kırılımındaki maç ve gol sayıları. Emin olunmayan hiçbir rakam yazılmadı;
 * `career` duraklarının `matches` ve `goals` alanları bu yüzden `null`.
 * Eksik bir satır, uydurma bir sayıdan iyidir.
 */
export const burakYilmaz: FavouritePlayer = {
  slug: "burak-yilmaz",
  name: "Burak Yılmaz",
  firstName: "BURAK",
  lastName: "YILMAZ",
  shirt: null,
  position: "Santrfor",
  club: "Galatasaray",
  clubShort: "GS",
  country: "Türkiye",
  countryCode: "TR",
  birthDate: "15 Temmuz 1985",
  birthPlace: "Antalya, Türkiye",
  height: "188 cm",
  weight: "—",
  tagline: "Kaleyi değil, maçın kendisini karşısına alan santrfor.",
  quote:
    "Kral lakabını taşımak, onu her maç yeniden hak etmek zorunda kalmak demekti.",
  closingQuote:
    "Otuz beşinde bir ülkeyi şampiyon yapan santrforun kariyeri, hiçbir yerde erken bitmemiş demektir.",
  palette: {
    ink: "#0b0709",
    accent: "#e02434",
    warm: "#e6b23f",
    glow: "rgba(224, 36, 52, 0.32)",
    neon: "#7d0d17",
  },
  hero: {
    id: "hero",
    src: `${BASE}/hero.jpg`,
    alt: "Burak Yılmaz, Galatasaray forması",
    placeholder: true,
    hint: "Dikey kadraj · GS forması · sert ışık · yüz net · bağıran ya da kollarını açan an",
    width: 1200,
    height: 1600,
  },
  card: {
    id: "card",
    src: `${BASE}/kart.jpg`,
    alt: "Burak Yılmaz",
    placeholder: true,
    hint: "Hub şeridindeki kart için · dikey · üst gövde · sakin bakış",
    width: 900,
    height: 1200,
  },
  badges: ["Santrfor", "Kral", "Galatasaray"],
  vitals: [
    { label: "Doğum tarihi", value: "15.07.1985" },
    { label: "Doğum yeri", value: "Antalya" },
    { label: "Uyruk", value: "Türkiye" },
    { label: "Boy", value: "188 cm" },
  ],
  storyTitle: ["Antalya'dan", "Avrupa'ya"],
  storyLede:
    "Geç açan bir santrforun hikâyesi: birkaç kulüp gezdikten sonra ligin en golcüsü, sonra Avrupa'nın en tanıdık stadyumlarında gol atan adam.",
  story: [
    "Antalya'da başladı ve uzun süre bir vaat olarak kaldı. Beşiktaş'a gitti, Manisaspor'a gitti, Fenerbahçe'ye gitti; her yerde iyiydi, hiçbir yerde vazgeçilmez değildi. Uzun gövdeli santrforlar geç olgunlaşır derler — o cümlenin canlı örneği gibiydi.",
    "Trabzonspor'da patladı. Bir sezon boyunca ligin en golcüsü oldu ve getirdiği şey sayı değil bir tavırdı: topu isteyen, sorumluluğu isteyen, kaybedince kimsenin arkasına saklanmayan bir forvet. 'Kral' lakabı o dönemde yapıştı ve bir daha çıkmadı.",
    "Galatasaray'a geldiğinde otuzuna yaklaşıyordu ve kariyerinin en görünür yılları hâlâ önündeydi. Şampiyonlar Ligi geceleri onu Türkiye'nin dışına taşıdı: Türk Telekom'da Manchester United, ardından iki maçlık bir Real Madrid turu. Avrupa adını burada öğrendi.",
    "Sonrası bir dolaşma daha oldu: Çin, dönüş, Beşiktaş, sonra Fransa. Lille'de otuz beş yaşında Ligue 1 şampiyonu oldu ve aynı dönemde A Milli Takım'ın kaptanıydı. Bir kariyerin en yüksek bölümünün en sona kalması nadirdir; onunki tam olarak öyle oldu.",
  ],
  stats: {
    club: {
      key: "galatasaray",
      label: "Galatasaray",
      crest: {
        id: "crest-gs",
        src: `${BASE}/arma-gs.png`,
        alt: "Galatasaray arması",
        placeholder: true,
        hint: "Galatasaray arması · kare ya da dikey · zemini temiz, kenarları net",
        width: 1000,
        height: 1200,
      },
      entries: [
        { key: "seasons", label: "Sezon", value: "4" },
        { key: "titles", label: "Süper Lig", value: "2" },
        { key: "cup", label: "Türkiye Kupası", value: "2" },
      ],
      note: "Maç ve gol sayıları doğrulanmadığı için bu kümeye yazılmadı; yalnızca emin olunan kupalar duruyor.",
    },
    all: {
      label: "Tüm zamanlar",
      entries: [
        { key: "topscorer", label: "Süper Lig gol kralı", value: "2" },
        { key: "ligue1", label: "Ligue 1", value: "1" },
        { key: "countries", label: "Ülke", value: "4" },
        { key: "national", label: "A Milli", value: "Kaptan" },
      ],
      note: "Türkiye, Çin, Fransa ve Hollanda. Kariyer toplamları doğrulanmadığı için buraya konmadı.",
    },
  },
  career: [
    {
      id: "antalyaspor",
      years: "2002 — 2006",
      club: "Antalyaspor",
      country: "Türkiye",
      note: "Profesyonel futbola doğduğu şehirde başladı; sonraki her adres bir arayıştı.",
      tone: "#8a5a34",
      matches: null,
      goals: null,
      image: {
        id: "career-antalyaspor",
        src: `${BASE}/kariyer-antalyaspor.jpg`,
        alt: "Burak Yılmaz, Antalyaspor formasıyla",
        placeholder: true,
        hint: "Antalyaspor forması · genç yıllar · yatay · arşiv karesi olabilir, düşük çözünürlük kabul",
        width: 1200,
        height: 675,
      },
    },
    {
      id: "trabzonspor",
      years: "2011 — 2012",
      club: "Trabzonspor",
      country: "Türkiye",
      note: "Bir sezonda ligin en golcüsü oldu; lakabı da o dönemde yerleşti.",
      tone: "#7b7365",
      matches: null,
      goals: null,
      image: {
        id: "career-trabzonspor",
        src: `${BASE}/kariyer-trabzonspor.jpg`,
        alt: "Burak Yılmaz, Trabzonspor formasıyla",
        placeholder: true,
        hint: "Trabzonspor forması · gol sevinci · yatay · rengi bastırılmış bir kare tercih edilir",
        width: 1200,
        height: 675,
      },
    },
    {
      id: "galatasaray",
      years: "2012 — 2016",
      club: "Galatasaray",
      country: "Türkiye",
      note: "Avrupa geceleri ve iki Süper Lig kupası; adı Türkiye'nin dışına burada çıktı.",
      tone: "#e6b23f",
      matches: null,
      goals: null,
      image: {
        id: "career-galatasaray",
        src: `${BASE}/kariyer-galatasaray.jpg`,
        alt: "Burak Yılmaz, Galatasaray formasıyla",
        placeholder: true,
        hint: "GS forması · gol sevinci · şeridin en güçlü karesi burası olmalı · yatay",
        width: 1200,
        height: 675,
      },
    },
    {
      id: "lille",
      years: "2020 — 2022",
      club: "Lille",
      country: "Fransa",
      note: "Otuz beşinde Fransa şampiyonluğu; kariyerinin en yüksek noktası en sonda geldi.",
      tone: "#c22030",
      matches: null,
      goals: null,
      current: true,
      image: {
        id: "career-lille",
        src: `${BASE}/kariyer-lille.jpg`,
        alt: "Burak Yılmaz, Lille formasıyla",
        placeholder: true,
        hint: "Lille forması · şampiyonluk kutlaması · yatay · kaptanlık bandı görünürse ideal",
        width: 1200,
        height: 675,
      },
    },
  ],
  nights: [
    {
      year: 2012,
      title: "Türk Telekom'da Manchester United",
      meta: "Şampiyonlar Ligi · Galatasaray — Manchester United",
      line: "Maçın tek golü ve o gol onundu. Avrupa'nın en çok tanınan formasının karşısında, stadyumun bir daha oturmadığı bir akşam.",
      image: {
        id: "night-manutd",
        src: `${BASE}/gece-manutd.jpg`,
        alt: "",
        placeholder: true,
        hint: "Türk Telekom Arena · GS forması · gol sevinci ya da tribün · yatay",
        width: 1200,
        height: 800,
      },
    },
    {
      year: 2013,
      title: "Real Madrid turu",
      meta: "Şampiyonlar Ligi çeyrek final · Galatasaray — Real Madrid",
      line: "Madrid'de kaybedilen tur İstanbul'da geri dönmeye çok yaklaştı. Tabela tersken gol atmak, gol atmanın en zor hâlidir.",
      image: {
        id: "night-realmadrid",
        src: `${BASE}/gece-realmadrid.jpg`,
        alt: "",
        placeholder: true,
        hint: "Real Madrid maçı · GS forması · gece ışığı · yatay",
        width: 1200,
        height: 800,
      },
    },
    {
      year: 2021,
      title: "Hollanda karşısında hat-trick",
      meta: "Dünya Kupası elemeleri · Türkiye — Hollanda",
      line: "Otuz beşindeydi ve kaptandı. O akşam üç gol attı; milli formayı taşımanın anlamı bir süre daha ona bağlandı.",
      image: {
        id: "night-hollanda",
        src: `${BASE}/gece-hollanda.jpg`,
        alt: "",
        placeholder: true,
        hint: "A Milli forma · kaptanlık bandı · gol sevinci · yatay",
        width: 1200,
        height: 800,
      },
    },
    {
      year: 2021,
      title: "Son hafta, Angers",
      meta: "Ligue 1 · Angers — Lille",
      line: "Şampiyonluk son maça ve deplasmana kalmıştı. Maç bittiğinde otuz beş yaşındaki santrfor çimlerin üstünde ağlıyordu; Lille on yıl sonra Fransa şampiyonuydu.",
      image: {
        id: "night-lille",
        src: `${BASE}/gece-lille.jpg`,
        alt: "",
        placeholder: true,
        hint: "Lille şampiyonluk günü · saha içi kutlama · yatay · duygusal kare",
        width: 1200,
        height: 800,
      },
    },
  ],
  personal: [
    {
      label: "Duruş",
      title: "Sırtı kaleye dönük",
      body: "Uzun gövdeyi savunmacıyla top arasına koyar ve ilk dokunuşu kendinden değil, rakipten uzağa atar. Böyle bir forveti düşürmeden durdurmak zordur. Ceza sahasının sırtı dönük hâlini seven az sayıda santrfordan biriydi.",
    },
    {
      label: "Otorite",
      title: "Topu ortadan o alır",
      body: "Gol yenildikten sonra topu kimseye vermez, ortaya kendi taşır. Küçük bir hareket ama takıma söylediği şey belli: oyunu yeniden başlatan benim. Kaptanlık pazubendi takmadan önce de böyleydi.",
    },
    {
      label: "Detay",
      title: "Sıçramadan önce yer tutmak",
      body: "Kafa topunda yükselmeyi değil, yükseleceği yeri kazanmayı önemser. Ortadan bir saniye önce vücudunu sokar, rakip zaten geç kalmıştır. Sıçrayış o işin sonu, başı değil.",
    },
  ],
  gallery: [
    {
      id: "gallery-1",
      src: `${BASE}/galeri-1.jpg`,
      alt: "Burak Yılmaz",
      placeholder: true,
      hint: "Ana galeri karesi · geniş · en yüksek çözünürlük · GS forması",
      width: 1600,
      height: 900,
      caption: "Ana kare",
    },
    {
      id: "gallery-2",
      src: `${BASE}/galeri-2.jpg`,
      alt: "Maç anı",
      placeholder: true,
      hint: "Maç anı · yatay · hareket hâlinde",
      width: 1200,
      height: 800,
      caption: "Maç anı",
    },
    {
      id: "gallery-3",
      src: `${BASE}/galeri-3.jpg`,
      alt: "Portre",
      placeholder: true,
      hint: "Portre · dikey · sert ışık · yüz yakın",
      width: 900,
      height: 1200,
      caption: "Portre",
    },
    {
      id: "gallery-4",
      src: `${BASE}/galeri-4.jpg`,
      alt: "Gol sevinci",
      placeholder: true,
      hint: "Gol sevinci · dikey · kollar açık ya da tribüne dönük",
      width: 900,
      height: 1200,
      caption: "Sevinç",
    },
    {
      id: "gallery-5",
      src: `${BASE}/galeri-5.jpg`,
      alt: "Kaptanlık",
      placeholder: true,
      hint: "Kaptanlık bandı görünen kare · A Milli ya da kulüp · yatay",
      width: 1200,
      height: 800,
      caption: "Kaptan",
    },
    {
      id: "gallery-6",
      src: `${BASE}/galeri-6.jpg`,
      alt: "Tribün",
      placeholder: true,
      hint: "Taraftar / tribün ile bir an · yatay ya da kare",
      width: 1200,
      height: 900,
      caption: "Tribün",
    },
    {
      id: "gallery-7",
      src: `${BASE}/galeri-7.jpg`,
      alt: "Kupa",
      placeholder: true,
      hint: "Kupa ya da şampiyonluk gecesi · dikey",
      width: 900,
      height: 1300,
      caption: "Kupa",
    },
  ],

  /**
   * Bebas'ın skorboard kondansesi, arşiv çerçevesi içinde bir portre ve zemini
   * kesen yatay tarama çizgileri. Sıkışık ritim ve film graini: köşeli, sert,
   * nefes vermeyen bir sayfa — anlattığı adam gibi.
   */
  design: {
    voice: "condensed",
    hero: "frame",
    signature: "scan",
    rhythm: "tight",
    texture: "grain",
  },
};
