import type { FavouritePlayer } from "./types";

/** Kareler bu klasörde bekliyor; küratörün yüklediği `/uploads/`de. */
const BASE = "/assets/players/davinson-sanchez";

/**
 * DAVINSON SÁNCHEZ — Kolombiyalı stoper.
 *
 * ⚠️ SAYILAR DOĞRULANMADI — dış bir kaynakla karşılaştırılmadı.
 * Küratör düzeltmesi bu dosyada tek satır.
 *
 * Bu kayıtta maç / gol / asist dökümü BİLEREK YOK. Emin olunmayan hiçbir
 * rakam yazılmadı: `career` duraklarının `matches` ve `goals` alanları `null`,
 * istatistik kümeleri yalnızca doğrulanabilir künye satırları taşıyor.
 *
 * ⚠️ Kariyerinde Tottenham var ve Tottenham'ın rengi bu arşivde yasak. Durak
 * nötr taş tonuyla (`#7b7365`) temsil ediliyor; dosyanın hiçbir yerinde mavi
 * bir değer yok.
 */
export const davinsonSanchez: FavouritePlayer = {
  slug: "davinson-sanchez",
  name: "Davinson Sánchez",
  firstName: "DAVINSON",
  lastName: "SÁNCHEZ",
  shirt: 6,
  position: "Stoper",
  club: "Galatasaray",
  clubShort: "GS",
  country: "Kolombiya",
  countryCode: "CO",
  birthDate: "12 Haziran 1996",
  birthPlace: "Caloto, Kolombiya",
  height: "187 cm",
  weight: "—",
  tagline: "Hatanın peşinden koşup onu yakalayan adam.",
  quote: "Bir stoperin en iyi maçı, adının hiç geçmediği maçtır.",
  closingQuote:
    "Savunmanın kahramanı yoktur; olmayan gol kimsenin hanesine yazılmaz. Bu defter onu yazıyor.",
  palette: {
    ink: "#100b06",
    accent: "#f2b619",
    warm: "#8a3a1c",
    glow: "rgba(242, 182, 25, 0.30)",
    neon: "#c8471d",
  },
  hero: {
    id: "hero",
    src: `${BASE}/hero.jpg`,
    alt: "Davinson Sánchez, Galatasaray forması",
    placeholder: true,
    hint: "Dikey kadraj · GS forması · gövde dili görünsün (hava topu ya da hattı hizalarken) · yüz net · kutlama değil",
    width: 1200,
    height: 1600,
  },
  card: {
    id: "card",
    src: `${BASE}/kart.jpg`,
    alt: "Davinson Sánchez",
    placeholder: true,
    hint: "Hub şeridindeki kart · dikey · üst gövde · sakin bakış, sert ışık",
    width: 900,
    height: 1200,
  },
  badges: ["Stoper", "No. 6", "Galatasaray"],
  vitals: [
    { label: "Doğum tarihi", value: "12.06.1996" },
    { label: "Uyruk", value: "Kolombiya" },
    { label: "Boy", value: "187 cm" },
    { label: "Mevki", value: "Stoper" },
  ],
  storyTitle: ["Kolombiya'nın", "son adamı"],
  storyLede:
    "Caloto'dan Medellín'e, Amsterdam'dan Londra'ya, oradan İstanbul'a. Dört kulüp, iki Avrupa finali ve hep en arkada duran tek bir adam.",
  story: [
    "Caloto, Kolombiya'nın güneybatısında şeker kamışı tarlalarının arasında küçük bir kasaba. Oradan Medellín'e, Atlético Nacional'in altyapısına gitti. Kolombiya'da bir çocuğun futbolla tanışması genelde önde başlar; o arkada kaldı ve orada kalmayı seçti.",
    "Yirmi yaşında Copa Libertadores kaldıran kadronun içindeydi. Güney Amerika'nın en sert kupasını kazanan bir savunmanın genç yarısı olmak, Avrupa'nın dikkatini çekmenin en kısa yoludur. Aynı yıl Amsterdam'a gitti.",
    "Ajax'ta tek sezon kaldı ve o sezon bir Avrupa finaliyle bitti. Yanındaki stoper on yedi yaşında bir çocuktu: Matthijs de Ligt. O kadro dağılırken herkes bir büyük kulübe gitti; onun adresi Londra oldu ve Tottenham'a kulübün o günkü rekor bonservisiyle imzaladı.",
    "İngiltere'de altı yıl. Bir Şampiyonlar Ligi finali gördü, yeni bir stadyumun açılışını gördü, rekor bonservisin ağırlığını da gördü — İngiltere bir savunmacıyı fiyatıyla yargılar. 2023'te İstanbul'a geldiğinde yirmi yedi yaşındaydı ve kariyerinin en istikrarlı dönemini burada kurdu: aynı mevki, aynı sakinlik, üst üste gelen kupalar.",
  ],
  stats: {
    club: {
      key: "galatasaray",
      label: "Galatasaray",
      crest: {
        id: "crest-gs",
        src: `${BASE}/arma-gs.png`,
        alt: "Galatasaray arması",
        placeholder: true,
        hint: "Galatasaray arması · kare ya da dikey · koyu zeminde temiz kenar · şeffaf zemin ideal",
        width: 900,
        height: 900,
      },
      entries: [
        { key: "arrival", label: "Geliş", value: "2023" },
        { key: "shirt", label: "Forma", value: "6" },
        { key: "position", label: "Mevki", value: "Stoper" },
      ],
      note: "Maç ve gol dökümü küratörü bekliyor — bu defterde doğrulanmamış rakam yazılmıyor.",
    },
    all: {
      label: "Tüm zamanlar",
      entries: [
        { key: "clubs", label: "Kulüp", value: "4" },
        { key: "finals", label: "Avrupa finali", value: "2" },
        { key: "libertadores", label: "Libertadores", value: "2016" },
      ],
      note: "İki kıtada dört kulüp; ikisi Avrupa finaline kadar giden kadrolar.",
    },
  },
  career: [
    {
      id: "atletico-nacional",
      years: "2013 — 2016",
      club: "Atlético Nacional",
      country: "Kolombiya",
      note: "Kariyerin en büyük kupası en başta geldi: yirmi yaşında Libertadores.",
      tone: "#3f7a4a",
      matches: null,
      goals: null,
      image: {
        id: "career-atletico-nacional",
        src: `${BASE}/kariyer-atletico-nacional.jpg`,
        alt: "Davinson Sánchez, Atlético Nacional formasıyla",
        placeholder: true,
        hint: "Yeşil-beyaz Nacional forması · genç yıllar · aksiyon ya da kupa gecesi · yatay",
        width: 1200,
        height: 800,
      },
    },
    {
      id: "ajax",
      years: "2016 — 2017",
      club: "Ajax",
      country: "Hollanda",
      note: "Tek sezon, tek çıkış: Amsterdam onu bir yılda Avrupa finaline taşıdı.",
      tone: "#a83a2b",
      matches: null,
      goals: null,
      image: {
        id: "career-ajax",
        src: `${BASE}/kariyer-ajax.jpg`,
        alt: "Davinson Sánchez, Ajax formasıyla",
        placeholder: true,
        hint: "Ajax forması · kırmızı-beyaz dikey bant · ikili mücadele · yatay",
        width: 1200,
        height: 800,
      },
    },
    {
      id: "tottenham",
      years: "2017 — 2023",
      club: "Tottenham Hotspur",
      country: "İngiltere",
      note: "Altı yıl, rekor bonservis ve bir savunmacının en zor sınavı: sabır.",
      tone: "#7b7365",
      matches: null,
      goals: null,
      image: {
        id: "career-tottenham",
        src: `${BASE}/kariyer-tottenham.jpg`,
        alt: "Davinson Sánchez, Tottenham formasıyla",
        placeholder: true,
        hint: "Beyaz iç saha forması · hava topu ya da müdahale · yatay · kadrajda mavi alan mümkün olduğunca az kalsın",
        width: 1200,
        height: 800,
      },
    },
    {
      id: "galatasaray",
      years: "2023 —",
      club: "Galatasaray",
      country: "Türkiye",
      note: "Otuzuna yaklaşırken bulduğu düzen. Hat artık onun sesiyle hizalanıyor.",
      tone: "#f2b619",
      matches: null,
      goals: null,
      current: true,
      image: {
        id: "career-galatasaray",
        src: `${BASE}/kariyer-galatasaray.jpg`,
        alt: "Davinson Sánchez, Galatasaray formasıyla",
        placeholder: true,
        hint: "GS forması · savunmada müdahale ya da şampiyonluk anı — şeridin en güçlü karesi burası · yatay",
        width: 1200,
        height: 800,
      },
    },
  ],
  nights: [
    {
      year: 2016,
      title: "Libertadores gecesi",
      meta: "Copa Libertadores finali · Atlético Nacional",
      line: "Yirmi yaşında bir stoper, kulübün yirmi yedi yıl sonra kaldırdığı ikinci Libertadores'in kadrosundaydı. Medellín o gece uyumadı.",
      image: {
        id: "night-libertadores",
        src: `${BASE}/gece-libertadores.jpg`,
        alt: "Atlético Nacional, Copa Libertadores kutlaması",
        placeholder: true,
        hint: "Nacional forması · kupa gecesi · konfeti ve tribün · yatay",
        width: 1200,
        height: 800,
      },
    },
    {
      year: 2017,
      title: "Stockholm",
      meta: "Avrupa Ligi finali · Ajax — Manchester United",
      line: "Ajax'ın stoper ikilisi o gece yirmi ve on yedi yaşındaydı. Kupa gitti, ikisinin de adresi değişti.",
      image: {
        id: "night-stockholm",
        src: `${BASE}/gece-stockholm.jpg`,
        alt: "Ajax, Avrupa Ligi finali",
        placeholder: true,
        hint: "Ajax forması · final gecesi · soğuk stadyum ışığı · yatay",
        width: 1200,
        height: 800,
      },
    },
    {
      year: 2024,
      title: "Copa América finali",
      meta: "Copa América · Kolombiya — Arjantin",
      line: "Kolombiya finale uzun bir yenilmezlik serisiyle geldi ve seri o gece bitti. Sarı formanın arkasında, o seriyi kuran savunmanın içindeydi.",
      image: {
        id: "night-copa-america",
        src: `${BASE}/gece-copa-america.jpg`,
        alt: "Davinson Sánchez, Kolombiya millî takım forması",
        placeholder: true,
        hint: "Kolombiya sarı millî forma · final gecesi · yatay · yüz net",
        width: 1200,
        height: 800,
      },
    },
    {
      year: 2024,
      title: "İlk şampiyonluk",
      meta: "Süper Lig · 2023-24",
      line: "İstanbul'daki ilk sezonu kupayla bitti. Savunmanın kahramanı olmaz; ama o gece kupanın altındaki eller arasında onunki de vardı.",
      image: {
        id: "night-sampiyonluk",
        src: `${BASE}/gece-sampiyonluk.jpg`,
        alt: "Galatasaray şampiyonluk kutlaması",
        placeholder: true,
        hint: "GS forması · şampiyonluk gecesi · kupa ya da tribün · yatay",
        width: 1200,
        height: 800,
      },
    },
  ],
  personal: [
    {
      label: "Alışkanlık",
      title: "Geri koşu",
      body: "Arkasına atılan topa dönerken adımını kısaltmaz, uzatır. Çoğu stoper o anda paniğe kapılıp yana açılır; o düz koşar ve forvetin omzunu bulur. Kaybedilmiş görünen topların yarısı böyle geri geliyor.",
    },
    {
      label: "Duruş",
      title: "Öne çıkan ayak",
      body: "Topu beklemez, karşılamaya çıkar. Riskli bir savunma biçimidir: bir kez yanılırsan arkan boş kalır. Yanılma payını kapatan şey hızı; bunu bildiği için çıkmaya devam ediyor.",
    },
    {
      label: "Detay",
      title: "Kaldırdığı kol",
      body: "Rakip ceza sahasına yaklaşırken kolunu kaldırıp hattı hizalıyor; kimse ona bakmasa bile yapıyor. Ofsayt çizgisi bir anlaşmadır ve o anlaşmayı her hücumda yeniden imzalıyor. Maçtan sonra kimsenin konuşmadığı iş tam olarak budur.",
    },
  ],
  gallery: [
    {
      id: "gallery-1",
      src: `${BASE}/galeri-1.jpg`,
      alt: "Davinson Sánchez",
      placeholder: true,
      hint: "Ana galeri karesi · geniş · en yüksek çözünürlük · GS forması",
      width: 1600,
      height: 900,
      caption: "Ana kare",
    },
    {
      id: "gallery-2",
      src: `${BASE}/galeri-2.jpg`,
      alt: "İkili mücadele",
      placeholder: true,
      hint: "İkili mücadele · omuz omuza · yatay",
      width: 1400,
      height: 933,
      caption: "Mücadele",
    },
    {
      id: "gallery-3",
      src: `${BASE}/galeri-3.jpg`,
      alt: "Portre",
      placeholder: true,
      hint: "Portre · dikey · sakin ifade · koyu zemin",
      width: 900,
      height: 1200,
      caption: "Portre",
    },
    {
      id: "gallery-4",
      src: `${BASE}/galeri-4.jpg`,
      alt: "Hava topu",
      placeholder: true,
      hint: "Hava topu · sıçrama anı · dikey",
      width: 900,
      height: 1200,
      caption: "Hava topu",
    },
    {
      id: "gallery-5",
      src: `${BASE}/galeri-5.jpg`,
      alt: "Kolombiya millî takım forması",
      placeholder: true,
      hint: "Millî forma · sarı · yatay",
      width: 1200,
      height: 800,
      caption: "Kolombiya",
    },
    {
      id: "gallery-6",
      src: `${BASE}/galeri-6.jpg`,
      alt: "Antrenman",
      placeholder: true,
      hint: "Antrenman · yatay ya da kare · gündüz ışığı",
      width: 1200,
      height: 800,
      caption: "Antrenman",
    },
    {
      id: "gallery-7",
      src: `${BASE}/galeri-7.jpg`,
      alt: "Kupa",
      placeholder: true,
      hint: "Kupa · şampiyonluk gecesi · dikey",
      width: 900,
      height: 1200,
      caption: "Kupa",
    },
  ],

  /**
   * Sütun hero: stoperin sayfası simetrik kurulur — ad üstte, portre altta,
   * ortada tek bir dikey eksen. Anton'un poster kapitali, çapraz imza bandı,
   * dengeli ritim ve film graini.
   */
  design: {
    voice: "poster",
    hero: "column",
    signature: "sash",
    rhythm: "open",
    texture: "grain",
  },
};
