import type { FavouritePlayer } from "./types";

/** Küratör bu klasöre yükleyecek; yuvaların hepsi şimdilik boş bekliyor. */
const BASE = "/assets/players/drogba";

/**
 * ⚠️ SAYILAR DOĞRULANMADI — dış bir kaynakla karşılaştırılmadı.
 * Küratör düzeltmesi bu dosyada tek satır.
 *
 * Bu kayıtta maç ve gol sayısı BİLEREK yazılmadı: kariyer duraklarının
 * `matches`/`goals` alanları `null`, istatistik kümelerinde yalnızca emin
 * olunan kupalar var. Boy dışında fiziksel ölçü yazılmadı (`weight: "—"`).
 * Uydurma bir rakam yerine eksik satır tercih edildi.
 */
export const didierDrogba: FavouritePlayer = {
  slug: "drogba",
  name: "Didier Drogba",
  firstName: "DIDIER",
  lastName: "DROGBA",
  shirt: 11,
  position: "Forvet",
  club: "Galatasaray",
  clubShort: "GS",
  country: "Fildişi Sahili",
  countryCode: "CI",
  birthDate: "11 Mart 1978",
  birthPlace: "Abidjan, Fildişi Sahili",
  height: "189 cm",
  weight: "—",
  tagline: "Stoperi kolunun üzerinde tutup takımının yetişmesini bekleyen adam.",
  quote:
    "Diz çöküp ülkesinden savaşı durdurmasını istediği gece, kazandığı hiçbir kupa o kadar büyük değildi.",
  closingQuote:
    "Kupalar rafta durur. O gece söylediği cümle hâlâ bir ülkenin içinde duruyor.",
  palette: {
    ink: "#100b07",
    accent: "#f07d21",
    warm: "#0f7a49",
    glow: "rgba(240, 125, 33, 0.32)",
    neon: "#a83c12",
  },
  hero: {
    id: "hero",
    src: `${BASE}/hero.jpg`,
    alt: "Didier Drogba, Galatasaray forması",
    placeholder: true,
    hint: "Dikey kadraj · GS forması · göğüsten yukarısı · sertlik ve sükûnet bir arada, gülümseme değil",
    width: 1200,
    height: 1600,
  },
  card: {
    id: "card",
    src: `${BASE}/kart.jpg`,
    alt: "Didier Drogba",
    placeholder: true,
    hint: "Hub şeridindeki kart · dikey · üst gövde · sarı-kırmızı net okunsun",
    width: 900,
    height: 1200,
  },
  badges: ["Forvet", "No. 11", "Galatasaray"],
  vitals: [
    { label: "Doğum tarihi", value: "11.03.1978" },
    { label: "Uyruk", value: "Fildişi Sahili" },
    { label: "Boy", value: "189 cm" },
    { label: "Mevki", value: "Forvet" },
  ],
  storyTitle: ["Abidjan'dan", "Münih'e"],
  storyLede:
    "Beş yaşında bir uçağa bindirilip Fransa'ya gönderildi ve yirmi beşine kadar adını kimse duymadı. Otuz dördünde Avrupa'nın en büyük kupasını getiren kafa vuruşu onundu.",
  story: [
    "Abidjan'da doğdu, beş yaşında Fransa'ya gönderildi. Onu alan kişi profesyonel futbolcu olan amcasıydı; amcası kulüp değiştirdikçe çocuk da şehir değiştirdi. Bir yıl bir kasaba, ertesi yıl başka bir kasaba. Futbolu bir akademide değil, sürekli yeni olduğu bahçelerde öğrendi.",
    "Profesyonelliğe geç başladı. Le Mans'ta alt ligde oynadı, asıl sıçramayı Guingamp'ta yaptı ve yirmi beş yaşında hâlâ Fransa'nın dışında adı geçmiyordu. Marsilya'da tek sezon kaldı, o tek sezonda takımı Avrupa'da finale kadar taşıdı. Ertesi yaz Chelsea onu kulüp rekoru bir bedelle aldı; bir futbolcunun bir yıl içinde anonimlikten rekor transfere geçmesi nadirdir.",
    "Chelsea'de mevkiyi yeniden tarif etti. Sırtı kaleye dönük topu alır, stoperi kolunun üzerinde tutar ve takımın geri kalanının yetişmesini beklerdi; hücumun saati oydu. Finallerde attığı goller ayrı bir liste hâline geldi. 2012'de Münih'te, seksen sekizinci dakikada bir kornerden gelen kafa vuruşuyla eşitledi ve o gecenin son penaltısını attı.",
    "Ülkesinde ise futbolcu olmaktan başka bir şeydi. Fildişi Sahili ilk kez Dünya Kupası'na gitmeyi garantilediği gece, kutlama yerine kamerayı çağırdı ve takımıyla birlikte diz çöküp savaşın durmasını istedi. 2013 Ocak'ında Galatasaray'a geldi: bir buçuk sezonda Süper Lig ve Türkiye Kupası kazandı, Şampiyonlar Ligi'nde eski kulübünün karşısına çıktı. Buradan ayrıldıktan sonra Chelsea'ye döndü ve bir lig şampiyonluğu daha ekledi.",
  ],
  stats: {
    club: {
      key: "galatasaray",
      label: "Galatasaray",
      crest: {
        id: "crest-gs",
        src: `${BASE}/arma-gs.png`,
        alt: "Galatasaray arması",
        placeholder: true,
        hint: "Galatasaray arması · kare ya da dikey · koyu zemin üzerinde temiz kenar",
        width: 800,
        height: 800,
      },
      entries: [
        { key: "years", label: "Yıl", value: "2013 — 2014" },
        { key: "league", label: "Süper Lig", value: "1" },
        { key: "cup", label: "Türkiye Kupası", value: "1" },
      ],
      note: "Bir buçuk sezon, iki kupa. Maç ve gol sayıları doğrulanmadığı için yazılmadı.",
    },
    all: {
      label: "Tüm zamanlar",
      entries: [
        { key: "premier", label: "Premier Lig", value: "4" },
        { key: "facup", label: "FA Kupası", value: "4" },
        { key: "ucl", label: "Şampiyonlar Ligi", value: "1" },
        { key: "africa", label: "Afrika'nın En İyisi", value: "2" },
      ],
      note: "Yalnızca emin olunan kupalar. Maç ve gol toplamları bilerek boş bırakıldı.",
    },
  },
  career: [
    {
      id: "guingamp",
      years: "2002 — 2003",
      club: "Guingamp",
      country: "Fransa",
      note: "Küçük bir kulüpte geç patlayan bir santrfor; ilk kez ona bakıldı.",
      tone: "#8e2321",
      matches: null,
      goals: null,
      image: {
        id: "career-guingamp",
        src: `${BASE}/kariyer-guingamp.jpg`,
        alt: "Drogba, Guingamp formasıyla",
        placeholder: true,
        hint: "Guingamp forması · yatay · genç yıllar · arşiv kalitesi olsa da olur",
        width: 1200,
        height: 675,
      },
    },
    {
      id: "marsilya",
      years: "2003 — 2004",
      club: "Olympique Marsilya",
      country: "Fransa",
      note: "Tek sezon kaldı ve o sezonda takımı Avrupa'da finale taşıdı.",
      tone: "#8d8778",
      matches: null,
      goals: null,
      image: {
        id: "career-marsilya",
        src: `${BASE}/kariyer-marsilya.jpg`,
        alt: "Drogba, Marsilya formasıyla",
        placeholder: true,
        hint: "Marsilya forması · yatay · mümkünse Vélodrome tribünü arkada",
        width: 1200,
        height: 675,
      },
    },
    {
      id: "chelsea",
      years: "2004 — 2012",
      club: "Chelsea",
      country: "İngiltere",
      note: "Sekiz yıl, bir kulüp kimliği ve finallerde biten bir gol listesi.",
      tone: "#6d6455",
      matches: null,
      goals: null,
      image: {
        id: "career-chelsea",
        src: `${BASE}/kariyer-chelsea.jpg`,
        alt: "Drogba, Chelsea formasıyla",
        placeholder: true,
        hint: "Chelsea forması · yatay · sırtı kaleye dönük top tutuşu ideal kare",
        width: 1200,
        height: 675,
      },
    },
    {
      id: "galatasaray",
      years: "2013 — 2014",
      club: "Galatasaray",
      country: "Türkiye",
      note: "Ocak ortasında geldi, gitmeden önce iki kupa bırakıp gitti.",
      tone: "#f07d21",
      matches: null,
      goals: null,
      current: true,
      image: {
        id: "career-galatasaray",
        src: `${BASE}/kariyer-galatasaray.jpg`,
        alt: "Drogba, Galatasaray formasıyla",
        placeholder: true,
        hint: "GS forması · yatay · gol sevinci — şeridin en güçlü karesi burası",
        width: 1200,
        height: 675,
      },
    },
  ],
  nights: [
    {
      year: 2004,
      title: "Avrupa'ya çıkış",
      meta: "UEFA Kupası · Olympique Marsilya",
      line: "Yirmi altı yaşında bir santrfor, bir kulübü tek sezonda Avrupa finaline taşıdı. Turnuvanın son turlarında topu ona verip beklemek bir taktik hâline gelmişti.",
      image: {
        id: "night-marsilya",
        src: `${BASE}/gece-marsilya.jpg`,
        alt: "Drogba, Marsilya formasıyla bir Avrupa gecesinde",
        placeholder: true,
        hint: "Marsilya forması · Avrupa gecesi · yatay · projektör ışığı",
        width: 1200,
        height: 800,
      },
    },
    {
      year: 2005,
      title: "Soyunma odasındaki çağrı",
      meta: "Dünya Kupası elemeleri · Fildişi Sahili",
      line: "Ülke ilk kez Dünya Kupası'na gitmeyi garantilemişti. Kutlamayı kesip kamerayı çağırdı, takımıyla birlikte diz çöktü ve savaşın durmasını istedi.",
      image: {
        id: "night-cagri",
        src: `${BASE}/gece-cagri.jpg`,
        alt: "Drogba, milli takım formasıyla",
        placeholder: true,
        hint: "Soyunma odası ya da milli takım forması · o gecenin karesi bulunamazsa turuncu forma portresi",
        width: 1200,
        height: 800,
      },
    },
    {
      year: 2012,
      title: "Münih",
      meta: "Şampiyonlar Ligi finali · Bayern — Chelsea",
      line: "Rakibin kendi stadyumunda, seksen sekizinci dakikada kornerden gelen topu ağlara gönderdi. Aynı gecenin son penaltısını da o attı.",
      image: {
        id: "night-munih",
        src: `${BASE}/gece-munih.jpg`,
        alt: "Drogba, Şampiyonlar Ligi finalinde",
        placeholder: true,
        hint: "Allianz Arena · Chelsea forması · kafa vuruşu ya da penaltı anı · yatay",
        width: 1200,
        height: 800,
      },
    },
    {
      year: 2014,
      title: "Eski evine karşı",
      meta: "Şampiyonlar Ligi son 16 · Galatasaray — Chelsea",
      line: "Sarı-kırmızı formayla eski kulübünün karşısına çıktı. Deplasman tribünü doksan dakika boyunca onun adını söyledi; sahada iki tarafın da alkışladığı tek futbolcu oydu.",
      image: {
        id: "night-chelsea",
        src: `${BASE}/gece-chelsea.jpg`,
        alt: "Drogba, Galatasaray formasıyla Chelsea maçında",
        placeholder: true,
        hint: "Türk Telekom Arena · GS forması · Chelsea maçı · tribün arkada görünsün",
        width: 1200,
        height: 800,
      },
    },
  ],
  personal: [
    {
      label: "Alışkanlık",
      title: "Sırtı kaleye dönük",
      body: "Topu ayağına almadan önce stoperi bulur, kolunu göğsüne koyar ve orada bir süre öylece durur. O bir saniye takımın geri kalanına koşma zamanı verir. Attığı gollerin çoğu aslında burada, topa dokunmadan önce başlar.",
    },
    {
      label: "Detay",
      title: "Kafa vuruşunda boyun",
      body: "Havaya çok yükselmez, işi boynuyla yapar. Topa değdiği an başını bir kez daha çevirir ve yön oradan çıkar. Münih'teki vuruş tam olarak bu: mesafe değil, son anda dönen bir boyun.",
    },
    {
      label: "Kusur",
      title: "Çok düşerdi",
      body: "Yere kolay gitmesi yıllarca eleştirildi ve eleştiri tümüyle haksız değildi. Ama her maçta üzerine iki stoper birden gelen bir gövdenin de kendi hesabı var. Bu satırı arşivden silmiyorum; kusursuz bir portre hiçbir zaman doğru bir portre olmuyor.",
    },
  ],
  gallery: [
    {
      id: "gallery-1",
      src: `${BASE}/galeri-1.jpg`,
      alt: "Didier Drogba",
      placeholder: true,
      hint: "Ana galeri karesi · geniş · en yüksek çözünürlük · GS forması tercih edilir",
      width: 1600,
      height: 900,
      caption: "Ana kare",
    },
    {
      id: "gallery-2",
      src: `${BASE}/galeri-2.jpg`,
      alt: "Maç anı",
      placeholder: true,
      hint: "Maç anı · yatay · top ayakta, gövde mücadelesi görünsün",
      width: 1200,
      height: 800,
      caption: "Maç anı",
    },
    {
      id: "gallery-3",
      src: `${BASE}/galeri-3.jpg`,
      alt: "Portre",
      placeholder: true,
      hint: "Portre · dikey · yüz net · yakın kadraj",
      width: 900,
      height: 1200,
      caption: "Portre",
    },
    {
      id: "gallery-4",
      src: `${BASE}/galeri-4.jpg`,
      alt: "Gol sevinci",
      placeholder: true,
      hint: "Gol sevinci · dikey · kollar açık, tribüne dönük",
      width: 900,
      height: 1200,
      caption: "Sevinç",
    },
    {
      id: "gallery-5",
      src: `${BASE}/galeri-5.jpg`,
      alt: "Tribün",
      placeholder: true,
      hint: "Tribün / taraftar · yatay · sarı-kırmızı kalabalık",
      width: 1200,
      height: 800,
      caption: "Tribün",
    },
    {
      id: "gallery-6",
      src: `${BASE}/galeri-6.jpg`,
      alt: "Milli takım",
      placeholder: true,
      hint: "Fildişi Sahili forması · turuncu · yatay ya da kare",
      width: 1200,
      height: 900,
      caption: "Fildişi Sahili",
    },
    {
      id: "gallery-7",
      src: `${BASE}/galeri-7.jpg`,
      alt: "Kupa",
      placeholder: true,
      hint: "Kupa · şampiyonluk gecesi · dikey",
      width: 900,
      height: 1200,
      caption: "Kupa",
    },
  ],

  /**
   * STACK + SASH: adın portrenin üstüne binmesi, bir posterin üzerine basılmış
   * isim gibi duruyor; imza motifi çapraz bant o posteri kesiyor. Anton'un
   * poster kapitali, açık ritim ve film graini — Fildişi Sahili turuncusu ve
   * yeşiliyle kurulmuş sıcak bir gece.
   */
  design: {
    voice: "poster",
    hero: "stack",
    signature: "sash",
    rhythm: "open",
    texture: "grain",
  },
};
