import type { FavouritePlayer } from "./types";

/** Kareler bu klasörde bekliyor; küratörün yüklediği `/uploads/`de. */
const BASE = "/assets/players/metin-oktay";

/**
 * ⚠️ SAYILAR DOĞRULANMADI — dış bir kaynakla karşılaştırılmadı.
 * Küratör düzeltmesi bu dosyada tek satır.
 *
 * Bu kayıt siyah-beyaz arşiv döneminden. Maç, gol ve asist toplamları
 * BİLEREK yazılmadı: 1950-60'ların lig kayıtları kaynaktan kaynağa değişiyor
 * ve uydurma bir rakam, boş bir satırdan çok daha kötü. İstatistik kümeleri
 * bu yüzden sayı yerine dönem, unvan ve künye taşıyor. Boy ve kilo "—".
 */
export const metinOktay: FavouritePlayer = {
  slug: "metin-oktay",
  name: "Metin Oktay",
  firstName: "METİN",
  lastName: "OKTAY",
  shirt: null,
  position: "Santrfor",
  club: "Galatasaray",
  clubShort: "GS",
  country: "Türkiye",
  countryCode: "TR",
  birthDate: "2 Şubat 1936",
  birthPlace: "İzmir",
  height: "—",
  weight: "—",
  tagline: "Siyah-beyaz karelerin hiçbirinde ayakları yerde değil.",
  legendEpithet: "Taçsız Kral",
  legendEra: "1955 — 1969",
  quote:
    "Kral lakabını alan çok futbolcu oldu; tacı olmayan tek kral o kaldı.",
  closingQuote:
    "Ondan sonra gelen her santrfora aynı soru soruldu: Metin Oktay olabilecek mi?",
  palette: {
    ink: "#0a0908",
    accent: "#a8842f",
    warm: "#cabfa8",
    glow: "rgba(168, 132, 47, 0.28)",
    neon: "#5c4a22",
  },
  hero: {
    id: "hero",
    src: `${BASE}/hero.jpg`,
    alt: "Metin Oktay, Galatasaray forması",
    placeholder: true,
    hint: "Dikey kadraj · siyah-beyaz arşiv karesi · GS forması · gövde tam boy görünsün · rötuşsuz, grenli hâli tercih",
    width: 1200,
    height: 1600,
  },
  card: {
    id: "card",
    src: `${BASE}/kart.jpg`,
    alt: "Metin Oktay",
    placeholder: true,
    hint: "Hub şeridindeki kart + efsaneler salonu portresi · dikey · üst gövde · yüz net · siyah-beyaz",
    width: 900,
    height: 1200,
  },
  badges: ["Santrfor", "Taçsız Kral", "Galatasaray"],
  vitals: [
    { label: "Doğum", value: "2 Şubat 1936" },
    { label: "Doğum yeri", value: "İzmir" },
    { label: "Vefat", value: "13 Eylül 1991" },
    { label: "Dönem", value: "1955 — 1969" },
  ],
  storyTitle: ["İzmir'den", "Ali Sami Yen'e"],
  storyLede:
    "İzmir'in mahalle sahalarından Ali Sami Yen'in orta yuvarlağına, oradan bir sezonluk İtalya'ya ve geri. Geriye kalan on dört yıl, siyah-beyaz karelerde duruyor.",
  story: [
    "1936'da İzmir'de doğdu. Futbolu mahalle sahalarında öğrendi, ilk profesyonel formasını da o şehirde giydi; İzmirspor'da oynarken İstanbul'un dikkatini çekti. 1955'te Galatasaray'a geldiğinde on dokuz yaşındaydı ve kulübün adıyla anılacak kadar uzun kalacağını kimse bilmiyordu.",
    "Geldiği yıllarda Türkiye'nin ulusal bir ligi bile yoktu; futbol şehir liglerinde oynanıyordu. 1959'da Millî Lig kurulunca gol listeleri açıldı ve yıllarca aynı adla açılmaya devam etti. “Taçsız Kral” lakabı bir kupadan gelmiyor — kimsenin ona vermediği, herkesin verdiği bir unvandı.",
    "1961'de İtalya'ya, Palermo'ya gitti. Türkiye'den Serie A'ya giden sayılı futbolcudan biriydi ve bir sezon sonra döndü. Dönüşü gidişinden daha çok konuşuldu: o dönemde İtalya'dan geri gelmek bir başarısızlık sayılırdı, onun için sadece eve dönmekti.",
    "1969'da, otuz üç yaşında bıraktı. 1991'de bir trafik kazasında öldü. Bugün Galatasaray'ın Florya'daki tesisleri onun adını taşıyor: kulübün her futbolcusu, her sabah o adın yazılı olduğu kapıdan geçerek antrenmana çıkıyor.",
  ],
  stats: {
    club: {
      key: "galatasaray",
      label: "Galatasaray",
      crest: {
        id: "crest-gs",
        src: `${BASE}/arma-gs.jpg`,
        alt: "Galatasaray arması",
        placeholder: true,
        hint: "Galatasaray arması · kare kadraj · tercihen dönemin arması ya da sade tek renk",
        width: 900,
        height: 900,
      },
      entries: [
        { key: "era", label: "Galatasaray yılları", value: "1955 — 1969" },
        { key: "title", label: "Unvan", value: "Taçsız Kral" },
        { key: "role", label: "Mevki", value: "Santrfor" },
        { key: "facility", label: "Adını taşıyan tesis", value: "Florya" },
      ],
      note: "Maç ve gol toplamı bu deftere yazılmadı; dönemin kayıtları birbirini tutmuyor.",
    },
    all: {
      label: "Tüm zamanlar",
      entries: [
        { key: "clubs", label: "Kulüpler", value: "İzmirspor · Galatasaray · Palermo" },
        { key: "abroad", label: "Yurt dışı", value: "Palermo · Serie A" },
        { key: "era", label: "Kariyer", value: "1950'ler — 1969" },
      ],
      note: "Rakamlar değil, sıfatlar kaldı. Sayıları küratör dolduracak.",
    },
  },
  career: [
    {
      id: "izmirspor",
      years: "1955 öncesi",
      club: "İzmirspor",
      country: "Türkiye",
      note: "İzmir'de başladı; İstanbul onu burada gördü.",
      tone: "#7b7365",
      matches: null,
      goals: null,
      image: {
        id: "career-izmirspor",
        src: `${BASE}/kariyer-izmirspor.jpg`,
        alt: "Metin Oktay, İzmir yılları",
        placeholder: true,
        hint: "En erken kare · İzmir dönemi · takım fotoğrafı olabilir · yatay · grenli arşiv",
        width: 1200,
        height: 800,
      },
    },
    {
      id: "galatasaray",
      years: "1955 — 1961",
      club: "Galatasaray",
      country: "Türkiye",
      note: "On dokuz yaşında geldi; birkaç sezonda ligin adı oldu.",
      tone: "#8e7a44",
      matches: null,
      goals: null,
      image: {
        id: "career-galatasaray",
        src: `${BASE}/kariyer-galatasaray.jpg`,
        alt: "Metin Oktay, Galatasaray formasıyla",
        placeholder: true,
        hint: "İlk Galatasaray dönemi · aksiyon karesi · yatay · siyah-beyaz",
        width: 1200,
        height: 800,
      },
    },
    {
      id: "palermo",
      years: "1961 — 1962",
      club: "Palermo",
      country: "İtalya",
      note: "Bir sezonluk İtalya. Dönüşü gidişinden çok konuşuldu.",
      tone: "#8a6a63",
      matches: null,
      goals: null,
      image: {
        id: "career-palermo",
        src: `${BASE}/kariyer-palermo.jpg`,
        alt: "Metin Oktay, Palermo formasıyla",
        placeholder: true,
        hint: "Palermo forması · İtalya dönemi · yatay · en zor bulunacak kare, bulunursa şeridin sürprizi",
        width: 1200,
        height: 800,
      },
    },
    {
      id: "galatasaray-donus",
      years: "1962 — 1969",
      club: "Galatasaray",
      country: "Türkiye",
      note: "Döndü ve bir daha çıkmadı; kariyerini burada kapattı.",
      tone: "#c79a3a",
      matches: null,
      goals: null,
      current: true,
      image: {
        id: "career-galatasaray-donus",
        src: `${BASE}/kariyer-galatasaray-donus.jpg`,
        alt: "Metin Oktay, Galatasaray formasıyla ikinci dönem",
        placeholder: true,
        hint: "İkinci Galatasaray dönemi · şeridin en güçlü karesi burası · gol anı ya da tribünle birlikte · yatay",
        width: 1200,
        height: 800,
      },
    },
  ],
  nights: [
    {
      year: 1955,
      title: "İzmir'den gelen çocuk",
      meta: "Transfer · İzmirspor'dan Galatasaray'a",
      line: "On dokuz yaşında İstanbul'a geldi ve on dört yıl sonra çıktı. O çıkışta artık kulübün adı ile onun adı yan yana yazılıyordu.",
      image: {
        id: "night-transfer",
        src: `${BASE}/gece-transfer.jpg`,
        alt: "",
        placeholder: true,
        hint: "En genç hâli · imza ya da ilk forma karesi · yatay · arşiv greni",
        width: 1200,
        height: 800,
      },
    },
    {
      year: 1959,
      title: "Ligin ilk yılı",
      meta: "Millî Lig · Türkiye'nin ilk ulusal ligi",
      line: "Türkiye 1959'da ilk ulusal ligini kurdu. Gol listeleri o yıl açıldı ve yıllarca aynı adla açılmaya devam etti.",
      image: {
        id: "night-ilk-lig",
        src: `${BASE}/gece-ilk-lig.jpg`,
        alt: "",
        placeholder: true,
        hint: "Kalabalık tribün önünde gol anı · dönemin stadı · yatay · mümkünse geniş açı",
        width: 1200,
        height: 800,
      },
    },
    {
      year: 1961,
      title: "Palermo",
      meta: "Serie A · İtalya",
      line: "Bir sezonluğuna Sicilya'ya gitti. Türkiye'den İtalya'ya giden futbolcuların sayısı o yıllarda bir elin parmaklarını geçmiyordu.",
      image: {
        id: "night-palermo",
        src: `${BASE}/gece-palermo.jpg`,
        alt: "",
        placeholder: true,
        hint: "İtalya dönemi · takım ya da stadyum karesi · yatay · yabancı arşivden gelebilir",
        width: 1200,
        height: 800,
      },
    },
    {
      year: 1969,
      title: "Veda",
      meta: "Son sezon · Galatasaray",
      line: "Otuz üç yaşında ayakkabılarını astı. Ondan sonra gelen her dokuz numara, istese de istemese de onunla ölçüldü.",
      image: {
        id: "night-veda",
        src: `${BASE}/gece-veda.jpg`,
        alt: "",
        placeholder: true,
        hint: "Veda karesi · sahada tek başına ya da takım arkadaşlarının omzunda · yatay",
        width: 1200,
        height: 800,
      },
    },
  ],
  personal: [
    {
      label: "Kadraj",
      title: "Yalnızca fotoğraftan",
      body: "Onu sahada izlemedim; bu defterde hiç canlı görmediğim tek futbolcu o. Elimde yalnızca siyah-beyaz kareler ve başkalarının anlattıkları var. Buradaki bölüm bu yüzden bir maç değerlendirmesi değil, bir arşiv gezisi.",
    },
    {
      label: "Alışkanlık",
      title: "Havada duran gövde",
      body: "Arşivdeki karelerin neredeyse hepsinde iki ayağı da yerden kesik. Yerde durduğu bir fotoğrafını bulmak, havada olduğu bir fotoğrafını bulmaktan zor. Bir futbolcunun nasıl oynadığını fotoğraflarının ortak noktasından çıkarabiliyorsanız, o oyuncunun bir imzası var demektir.",
    },
    {
      label: "Kapı",
      title: "Florya'daki tabela",
      body: "Kulübün tesisleri onun adını taşıyor. Bir futbolcunun adının kapıya yazılması, o adın artık tek bir insana ait olmadığı anlamına geliyor. Her sabah oradan geçen genç oyuncuların çoğu onu hiç izlemedi — ama adını her gün okuyorlar.",
    },
  ],
  gallery: [
    {
      id: "gallery-1",
      src: `${BASE}/galeri-1.jpg`,
      alt: "Metin Oktay",
      placeholder: true,
      hint: "Ana galeri karesi · en yüksek çözünürlüklü arşiv fotoğrafı · yatay",
      width: 1280,
      height: 853,
      caption: "Ana kare",
    },
    {
      id: "gallery-2",
      src: `${BASE}/galeri-2.jpg`,
      alt: "Portre",
      placeholder: true,
      hint: "Portre · dikey · yüz net · stüdyo ya da forma çekimi",
      width: 900,
      height: 1200,
      caption: "Portre",
    },
    {
      id: "gallery-3",
      src: `${BASE}/galeri-3.jpg`,
      alt: "Maç anı",
      placeholder: true,
      hint: "Havada bir vuruş · rövaşata ya da uçarak kafa · yatay · sayfanın imza karesi",
      width: 1200,
      height: 800,
      caption: "Havada",
    },
    {
      id: "gallery-4",
      src: `${BASE}/galeri-4.jpg`,
      alt: "Takım fotoğrafı",
      placeholder: true,
      hint: "Dönemin takım fotoğrafı · yatay · ön sırada oturuyorsa ideal",
      width: 1400,
      height: 900,
      caption: "Takım",
    },
    {
      id: "gallery-5",
      src: `${BASE}/galeri-5.jpg`,
      alt: "Tribün",
      placeholder: true,
      hint: "Dönemin tribünü · şapkalı kalabalık · yatay · oyuncu kadrajda olmayabilir",
      width: 1200,
      height: 800,
      caption: "Tribün",
    },
    {
      id: "gallery-6",
      src: `${BASE}/galeri-6.jpg`,
      alt: "Gazete kupürü",
      placeholder: true,
      hint: "Dönemin gazete sayfası ya da afiş · dikey · okunacak kadar net",
      width: 900,
      height: 1300,
      caption: "Kupür",
    },
    {
      id: "gallery-7",
      src: `${BASE}/galeri-7.jpg`,
      alt: "Anma",
      placeholder: true,
      hint: "Heykel, tabela ya da Florya'daki adı · bugünden çekilmiş tek kare · dikey ya da kare",
      width: 1000,
      height: 1000,
      caption: "Adı",
    },
  ],

  /**
   * Metin Oktay'ın iskeleti ANIT: Cinzel'in kitabe sesi, adın portrenin üstüne
   * bindiği katmanlı poster (`stack`), yatay tarama izi (`scan`) ve arşiv
   * dokusu. Sayfa GECELERLE açılıyor — burada hikâye önce sahneden anlatılıyor,
   * künye sonra geliyor. Bu değerler merkezden dağıtıldı; değiştirilmiyor.
   */
  design: {
    voice: "monument",
    hero: "stack",
    signature: "scan",
    rhythm: "cinematic",
    texture: "archive",
    order: ["geceler", "hikaye", "kariyer", "anlar", "istatistik", "galeri"],
  },
};
