import type { FavouritePlayer } from "./types";

/** Küratörün yükleyeceği kareler bu klasörde bekliyor. */
const BASE = "/assets/players/osimhen";

/**
 * VICTOR OSIMHEN — Nijeryalı santrfor.
 *
 * ⚠️ SAYILAR DOĞRULANMADI — dış bir kaynakla karşılaştırılmadı.
 * Küratör düzeltmesi bu dosyada tek satır.
 *
 * Bu kayıtta maç / gol / asist sayısı BİLEREK yazılmadı. Emin olunmayan her
 * rakamın yerine satır hiç konmadı ya da `null` bırakıldı (sözleşme §5).
 * İstatistik kümelerinde yalnızca unvan, kupa ve yıl var; kariyer duraklarının
 * `matches` ve `goals` alanları küratörün doldurması için `null`.
 *
 * ⚠️ Napoli mavi bir kulüp. Kariyer şeridinde nötr taş tonuyla temsil ediliyor
 * (sözleşme §3). Sayfanın hiçbir yerinde mavi ton yok.
 */
export const victorOsimhen: FavouritePlayer = {
  slug: "osimhen",
  name: "Victor Osimhen",
  firstName: "VICTOR",
  lastName: "OSIMHEN",
  shirt: 45,
  position: "Santrfor",
  club: "Galatasaray",
  clubShort: "GS",
  country: "Nijerya",
  countryCode: "NG",
  birthDate: "29 Aralık 1998",
  birthPlace: "Lagos, Nijerya",
  height: "185 cm",
  weight: "—",
  tagline: "Boşluğu, o boşluk açılmadan önce gören adam.",
  quote: "Topa değil, savunmanın arkasına koşar; top oraya sonradan gelir.",
  closingQuote: "Maske yüzünü kapattı, oyununu hiç kapatmadı.",
  palette: {
    ink: "#0a0f0b",
    accent: "#1fb85a",
    warm: "#e6a11e",
    glow: "rgba(31, 184, 90, 0.34)",
    neon: "#0c6a3a",
  },
  hero: {
    id: "hero",
    src: `${BASE}/hero.jpg`,
    alt: "Victor Osimhen, Galatasaray forması",
    placeholder: true,
    hint: "Dikey kadraj · GS forması · maske görünsün · koşu ya da gol sevinci · yüz net",
    width: 1200,
    height: 1600,
  },
  card: {
    id: "card",
    src: `${BASE}/kart.jpg`,
    alt: "Victor Osimhen",
    placeholder: true,
    hint: "Hub şeridindeki kart için · dikey · üst gövde · sade zemin",
    width: 900,
    height: 1200,
  },
  badges: ["Santrfor", "No. 45", "Galatasaray"],
  vitals: [
    { label: "Doğum tarihi", value: "29.12.1998" },
    { label: "Uyruk", value: "Nijerya" },
    { label: "Boy", value: "185 cm" },
    { label: "Forma", value: "45" },
  ],
  storyTitle: ["Lagos'tan", "maskeye"],
  storyLede:
    "Lagos'un kenar mahallesinden çıkıp Napoli'ye otuz üç yıllık bir bekleyişi bitiren santrforun yolu; ve o yolun ortasında yüzüne taktığı zırh.",
  story: [
    "Lagos'ta, Olusosun'da büyüdü. Çocukluğu sokakta geçti: sabah satılacak bir şey bulmak, akşam boş bir alanda oynamak. Annesini çok küçükken kaybetti; ev ağabeylerinin sırtında ayakta kaldı. Futbolu bir kaçış olarak değil, bir iş olarak öğrendi.",
    "Adını 2015'te Şili'deki U-17 Dünya Kupası'nda duyurdu: Nijerya turnuvayı kazandı, o da turnuvanın gol rekorunu kırdı. Henüz on yedisine girmemişti ve Avrupa'nın bütün listelerine girmişti. Wolfsburg'a gitti, orada hiçbir şey yürümedi — ne dil, ne kadro, ne oyun. Vitrin oyuncusundan yedek kulübesine bir yıl içinde düştü.",
    "Belçika'ya, Charleroi'ya kiralanmak onu geri getirdi. Oradan Lille'e, Lille'den Napoli'ye — kulübün o güne kadarki en pahalı transferi olarak. İtalya'da önce yüzü kırıldı: San Siro'da bir hava topunda elmacık kemiği ve göz çevresi gitti. Sahaya maskeyle döndü ve maske uzun süre yüzünden inmedi.",
    "2022-23'te Napoli 1990'dan beri ilk kez şampiyon oldu; ligin gol kralı da oydu. Aynı yılın sonunda Afrika'nın yılın futbolcusu seçildi. 2024'te kiralık olarak İstanbul'a geldi ve ilk sezonunda Galatasaray ligi ve kupayı birlikte aldı. Ertesi yaz sözleşme kalıcı oldu; tribün için mesele rakam değildi, kalması meselesiydi.",
  ],
  stats: {
    club: {
      key: "galatasaray",
      label: "Galatasaray",
      crest: {
        id: "crest-gs",
        src: `${BASE}/arma-gs.png`,
        alt: "Galatasaray arması",
        placeholder: true,
        hint: "Galatasaray arması · kare ya da dikey · şeffaf zemin tercih edilir",
        width: 600,
        height: 600,
        credit: null,
      },
      entries: [
        { key: "arrival", label: "Geliş", value: "2024" },
        { key: "permanent", label: "Kalıcı transfer", value: "2025" },
        { key: "titles", label: "Şampiyonluk", value: "1" },
        { key: "cups", label: "Türkiye Kupası", value: "1" },
      ],
      note: "Maç ve gol sayısı bilerek boş: doğrulanmadan yazılmadı.",
    },
    all: {
      label: "Tüm zamanlar",
      entries: [
        { key: "seriea", label: "Serie A", value: "1" },
        { key: "capocannoniere", label: "Serie A gol kralı", value: "1" },
        { key: "caf", label: "Afrika'nın en iyisi", value: "2023" },
        { key: "u17", label: "U-17 Dünya Kupası", value: "2015" },
      ],
      note: "Unvanlar sayılabilir; kariyer maç ve gol toplamı doğrulanmadan buraya yazılmadı.",
    },
  },
  career: [
    {
      id: "wolfsburg",
      years: "2017 — 2018",
      club: "VfL Wolfsburg",
      country: "Almanya",
      note: "Avrupa'nın ilk kapısı ve ilk duvarı; oyun burada hiç tutmadı.",
      tone: "#4c6a33",
      matches: null,
      goals: null,
      image: {
        id: "career-wolfsburg",
        src: `${BASE}/kariyer-wolfsburg.jpg`,
        alt: "Osimhen, Wolfsburg formasıyla",
        placeholder: true,
        hint: "Wolfsburg forması · yatay · aksiyon ya da yedek kulübesi",
        width: 1200,
        height: 800,
      },
    },
    {
      id: "charleroi",
      years: "2018 — 2019",
      club: "Sporting Charleroi",
      country: "Belçika",
      note: "Bir sezonluk kiralık; kaybettiği golcülüğü burada geri aldı.",
      tone: "#57524a",
      matches: null,
      goals: null,
      image: {
        id: "career-charleroi",
        src: `${BASE}/kariyer-charleroi.jpg`,
        alt: "Osimhen, Charleroi formasıyla",
        placeholder: true,
        hint: "Charleroi forması · yatay · gol sevinci tercih edilir",
        width: 1200,
        height: 800,
      },
    },
    {
      id: "lille",
      years: "2019 — 2020",
      club: "Lille",
      country: "Fransa",
      note: "Tek sezon yetti; Fransa onu Avrupa'nın gündemine geri koydu.",
      tone: "#a3312a",
      matches: null,
      goals: null,
      image: {
        id: "career-lille",
        src: `${BASE}/kariyer-lille.jpg`,
        alt: "Osimhen, Lille formasıyla",
        placeholder: true,
        hint: "Lille forması · yatay · hızlanma anı",
        width: 1200,
        height: 800,
      },
    },
    {
      id: "napoli",
      years: "2020 — 2024",
      club: "Napoli",
      country: "İtalya",
      note: "Otuz üç yıl sonra gelen şampiyonluk ve ligin gol krallığı.",
      tone: "#7b7365",
      matches: null,
      goals: null,
      image: {
        id: "career-napoli",
        src: `${BASE}/kariyer-napoli.jpg`,
        alt: "Osimhen, Napoli formasıyla",
        placeholder: true,
        hint: "Napoli forması · maskeli kare · yatay · şeridin en tanıdık görüntüsü",
        width: 1200,
        height: 800,
      },
    },
    {
      id: "galatasaray",
      years: "2024 —",
      club: "Galatasaray",
      country: "Türkiye",
      note: "Kiralık geldi, çift kupayla başladı, ertesi yaz kalıcı oldu.",
      tone: "#e6a11e",
      matches: null,
      goals: null,
      current: true,
      image: {
        id: "career-galatasaray",
        src: `${BASE}/kariyer-galatasaray.jpg`,
        alt: "Osimhen, Galatasaray formasıyla",
        placeholder: true,
        hint: "GS forması · gol sevinci · şeridin en güçlü karesi burası olmalı",
        width: 1200,
        height: 800,
      },
    },
  ],
  nights: [
    {
      year: 2015,
      title: "Şili'deki turnuva",
      meta: "U-17 Dünya Kupası · Nijerya",
      line: "Bir turnuvada gol rekoru ve elinde kupayla biten bir final. Henüz on yedisine girmemiş bir çocuğun adı, o üç haftada Avrupa'nın bütün defterlerine geçti.",
      image: {
        id: "night-u17",
        src: `${BASE}/gece-u17.jpg`,
        alt: "Osimhen, Nijerya U-17 formasıyla",
        placeholder: true,
        hint: "Nijerya genç millî forması · yeşil · kupa ya da gol sevinci",
        width: 1200,
        height: 800,
      },
    },
    {
      year: 2021,
      title: "Maskenin doğduğu gece",
      meta: "Serie A · Inter — Napoli · San Siro",
      line: "Bir hava topunda yüzü kırıldı ve sezonu bitti sanıldı. Döndüğünde yüzünde bir maske vardı; o maske sonra oyunundan daha tanıdık oldu.",
      image: {
        id: "night-san-siro",
        src: `${BASE}/gece-san-siro.jpg`,
        alt: "Osimhen, sakatlık dönüşü maskesiyle",
        placeholder: true,
        hint: "Maskeli ilk dönüş karesi · yakın plan · yatay",
        width: 1200,
        height: 800,
      },
    },
    {
      year: 2023,
      title: "Otuz üç yıllık bekleyiş",
      meta: "Serie A · 2022-23 · Napoli",
      line: "Napoli 1990'dan beri ilk kez şampiyon oldu ve ligin gol kralı onun formasını taşıyordu. O gece şehirde kimse evde değildi.",
      image: {
        id: "night-scudetto",
        src: `${BASE}/gece-scudetto.jpg`,
        alt: "Napoli şampiyonluk kutlaması",
        placeholder: true,
        hint: "Şampiyonluk kutlaması · geniş kadraj · tribün ya da sokak",
        width: 1400,
        height: 900,
      },
    },
    {
      year: 2025,
      title: "İlk sezonda çift kupa",
      meta: "Süper Lig ve Türkiye Kupası · 2024-25",
      line: "İstanbul'a kiralık geldiği sezon lig ve kupa birlikte geldi. Bir yabancının ilk yılında bunu yapması burada uzun süre konuşulur.",
      image: {
        id: "night-super-lig",
        src: `${BASE}/gece-super-lig.jpg`,
        alt: "Osimhen, Galatasaray kupa gecesinde",
        placeholder: true,
        hint: "GS forması · kupa gecesi · konfeti ya da tribün · yatay",
        width: 1400,
        height: 900,
      },
    },
  ],
  personal: [
    {
      label: "Koşu",
      title: "Pas verilmeden önce",
      body: "Topu bekleyen bir santrfor değil. Orta sahadaki oyuncu başını kaldırmadan koşuyu başlatır; savunmacı topa bakarken o çoktan omzunun arkasındadır. Bu yüzden çok ofsayta düşer — ve düştüğü on ofsaydın birinde savunma bir daha toparlanamaz.",
    },
    {
      label: "Maske",
      title: "Çıkarmadığı zırh",
      body: "Kırık iyileştikten sonra da maskeyi uzun süre taktı. Bir korumadan çıkıp bir imzaya döndü: kadraja giren ilk şey yüzü değil, maskenin çizgisi oldu. Gol attıktan sonra onu yukarı ittiği an, arşivin en çok tekrarlanan karesi.",
    },
    {
      label: "Detay",
      title: "Omuz",
      body: "İkili mücadelede kolunu değil omzunu kullanır. Stoperin göğsüne yaslanıp yarım metre kazanır, sonra o yarım metreyi ilk dokunuşta ikiye katlar. Hakem faul saymaz; savunmacı maçtan sonra anlatır.",
    },
  ],
  gallery: [
    {
      id: "gallery-1",
      src: `${BASE}/galeri-1.jpg`,
      alt: "Victor Osimhen",
      placeholder: true,
      hint: "Ana galeri karesi · geniş · GS forması · en yüksek çözünürlük",
      width: 1600,
      height: 900,
      caption: "Ana kare",
    },
    {
      id: "gallery-2",
      src: `${BASE}/galeri-2.jpg`,
      alt: "Maskeli portre",
      placeholder: true,
      hint: "Maskeli portre · yakın plan · gözler net",
      width: 1000,
      height: 1000,
      caption: "Maske",
    },
    {
      id: "gallery-3",
      src: `${BASE}/galeri-3.jpg`,
      alt: "Gol sevinci",
      placeholder: true,
      hint: "Gol sevinci · dikey · kollar açık · tribüne dönük",
      width: 900,
      height: 1200,
      caption: "Sevinç",
    },
    {
      id: "gallery-4",
      src: `${BASE}/galeri-4.jpg`,
      alt: "Hava topu",
      placeholder: true,
      hint: "Kafa vuruşu · yatay · ayaklar yerden kesik",
      width: 1400,
      height: 900,
      caption: "Sıçrama",
    },
    {
      id: "gallery-5",
      src: `${BASE}/galeri-5.jpg`,
      alt: "Napoli yılları",
      placeholder: true,
      hint: "Napoli dönemi · arşiv karesi · yatay",
      width: 1200,
      height: 800,
      caption: "Napoli",
    },
    {
      id: "gallery-6",
      src: `${BASE}/galeri-6.jpg`,
      alt: "Nijerya millî forması",
      placeholder: true,
      hint: "Nijerya millî forması · yeşil · yatay · millî maç anı",
      width: 1200,
      height: 800,
      caption: "Nijerya",
    },
    {
      id: "gallery-7",
      src: `${BASE}/galeri-7.jpg`,
      alt: "Kupa gecesi",
      placeholder: true,
      hint: "Kupa · şampiyonluk gecesi · geniş kadraj",
      width: 1400,
      height: 1000,
      caption: "Kupa",
    },
  ],

  /**
   * Osimhen'in imzası KINETIC: portre kadrajı yararak çıkıyor, arkada yön
   * çizgileri. Anton'un poster kapitali, projektör huzmeleri, sıkışık ritim ve
   * dokusuz keskin zemin — hız ve fizik üzerine kurulu bir sayfa.
   * Bölüm sırası varsayılan; `order` bilerek yazılmadı.
   */
  design: {
    voice: "poster",
    hero: "kinetic",
    signature: "rays",
    rhythm: "tight",
    texture: "clean",
  },
};
