import type { FavouritePlayer } from "./types";

/** Kareler bu klasörde bekliyor; küratörün yüklediği dosyalar `/uploads/`de. */
const BASE = "/assets/players/sallai";

/**
 * ⚠️ SAYILAR DOĞRULANMADI — dış bir kaynakla karşılaştırılmadı.
 * Küratör düzeltmesi bu dosyada tek satır.
 *
 * Bu kayıtta bilerek YAZILMAYAN sayılar var: hiçbir kulüpteki maç/gol/asist
 * toplamı, forma numarası ve kilo. Emin olunmadığı için satır hiç konmadı;
 * `career` duraklarının `matches`/`goals` alanları `null` bırakıldı.
 */
export const rolandSallai: FavouritePlayer = {
  slug: "sallai",
  name: "Roland Sallai",
  firstName: "ROLAND",
  lastName: "SALLAI",
  shirt: null,
  position: "Kanat",
  club: "Galatasaray",
  clubShort: "GS",
  country: "Macaristan",
  countryCode: "HU",
  birthDate: "22 Mayıs 1997",
  birthPlace: "Budapeşte, Macaristan",
  height: "184 cm",
  weight: "—",
  tagline: "Kenardan başlar, kaleye en kısa çizgiyi arar.",
  quote: "Topu aldığı yerde durmaz; hep bir yön seçer ve o yöne koşar.",
  closingQuote:
    "Kanat bir mevki değil, bir karakterdir: sahanın kenarında doğar, ortasında bitirmek ister.",
  palette: {
    ink: "#0b0e0c",
    accent: "#3fae6d",
    warm: "#cd2a3e",
    glow: "rgba(63, 174, 109, 0.32)",
    neon: "#7f1d2c",
  },
  hero: {
    id: "hero",
    src: `${BASE}/hero.jpg`,
    alt: "Roland Sallai, Galatasaray forması",
    placeholder: true,
    hint: "Dikey kadraj · GS forması · koşu hâlinde, gövde öne eğik · yüz net",
    width: 1200,
    height: 1600,
  },
  card: {
    id: "card",
    src: `${BASE}/kart.jpg`,
    alt: "Roland Sallai",
    placeholder: true,
    hint: "Hub şeridindeki kart için · dikey · üst gövde · sakin bakış",
    width: 900,
    height: 1200,
  },
  badges: ["Kanat", "Macaristan", "Galatasaray"],
  vitals: [
    { label: "Doğum tarihi", value: "22.05.1997" },
    { label: "Uyruk", value: "Macaristan" },
    { label: "Mevki", value: "Kanat" },
    { label: "Boy", value: "184 cm" },
  ],
  storyTitle: ["Kanattan", "içeriye"],
  storyLede:
    "Budapeşte'den Palermo'ya, Lefkoşa'dan Freiburg'a: bir kanat oyuncusunun yolu düz gitmedi, ama her durakta aynı şeyi yaptı — çizgiyi kısalttı.",
  story: [
    "Budapeşte'de doğdu ve futbolu Puskás Akadémia'da öğrendi. Soyadı Macar futbolunda yeni değildi: babası Sándor Sallai millî formayı giymiş bir savunmacıydı. Aynı soyadını sahaya ikinci kuşakta geri getirmek, bir çocuğun sırtına erken binen bir yüktür.",
    "On sekiz yaşında İtalya'ya, Palermo'ya gitti. Serie A bir genç kanat için doğru okul ama yanlış zamandı; sahada geçirdiği süre, kulübede geçirdiği sürenin yanında kısa kaldı. O yıl öğrendiği şey teknik değil, sabırdı.",
    "Sonra kimsenin kariyer planına yazmayacağı bir adım attı ve Kıbrıs'a, APOEL'e gitti. Şampiyonluk kazandı, Avrupa'yı ilk kez içeriden gördü. Bir oyuncunun gelişimi için oynamak, hangi ligde oynadığından önce gelir; bunu erken anladı.",
    "Almanya yedi yıl sürdü. Freiburg'da kanat oyuncusu olmanın yarısının topsuz koşu olduğunu öğrendi: baskı, geri dönüş, aynı koşuyu doksan dakika boyunca tekrar tekrar yapmak. İstanbul'a geldiğinde artık sadece hızlı bir çocuk değildi — nereye koşacağını bilen bir oyuncuydu.",
  ],
  stats: {
    club: {
      key: "galatasaray",
      label: "Galatasaray",
      crest: {
        id: "crest-gs",
        src: `${BASE}/arma-gs.png`,
        alt: "Galatasaray arması",
        placeholder: true,
        hint: "Galatasaray arması · kare ya da dikey · şeffaf zemin ideal",
        width: 800,
        height: 800,
      },
      entries: [
        { key: "since", label: "Katılım", value: "2025" },
        { key: "from", label: "Geldiği kulüp", value: "Freiburg" },
        { key: "role", label: "Mevki", value: "Kanat" },
        { key: "country", label: "Uyruk", value: "Macaristan" },
      ],
      note: "Maç ve gol sayıları burada boş: doğrulanmadan rakam yazılmadı.",
    },
    all: {
      label: "Tüm zamanlar",
      entries: [
        { key: "born", label: "Doğum", value: "1997" },
        { key: "national", label: "Millî takım", value: "Macaristan" },
        { key: "euro", label: "EURO", value: "2020 · 2024" },
      ],
      note: "Palermo, APOEL, Freiburg ve Galatasaray. Toplamlar doğrulanmadı.",
    },
  },
  career: [
    {
      id: "palermo",
      years: "2015 — 2016",
      club: "Palermo",
      country: "İtalya",
      note: "On sekizinde Serie A: az oynadı, çok gördü.",
      tone: "#a3596a",
      matches: null,
      goals: null,
      image: {
        id: "career-palermo",
        src: `${BASE}/kariyer-palermo.jpg`,
        alt: "Roland Sallai, Palermo formasıyla",
        placeholder: true,
        hint: "Palermo forması · pembe-siyah görünsün · genç yüz · yatay",
        width: 1200,
        height: 800,
      },
    },
    {
      id: "apoel",
      years: "2016 — 2018",
      club: "APOEL",
      country: "Kıbrıs",
      note: "Şampiyonluk ve Avrupa'nın ilk kez içeriden görülmesi.",
      tone: "#8f7b34",
      matches: null,
      goals: null,
      image: {
        id: "career-apoel",
        src: `${BASE}/kariyer-apoel.jpg`,
        alt: "Roland Sallai, APOEL formasıyla",
        placeholder: true,
        hint: "APOEL forması · sarı ağır bassın · maç anı · yatay",
        width: 1200,
        height: 800,
      },
    },
    {
      id: "freiburg",
      years: "2018 — 2025",
      club: "SC Freiburg",
      country: "Almanya",
      note: "Yedi yıl. Topsuz koşunun mevkinin yarısı olduğu yer.",
      tone: "#a92f2b",
      matches: null,
      goals: null,
      image: {
        id: "career-freiburg",
        src: `${BASE}/kariyer-freiburg.jpg`,
        alt: "Roland Sallai, Freiburg formasıyla",
        placeholder: true,
        hint: "Freiburg forması · kırmızı-siyah · sprint hâlinde · yatay",
        width: 1200,
        height: 800,
      },
    },
    {
      id: "galatasaray",
      years: "2025 —",
      club: "Galatasaray",
      country: "Türkiye",
      note: "Yirmi sekizinde, artık nereye koşacağını bilerek geldi.",
      tone: "#e9a72c",
      matches: null,
      goals: null,
      current: true,
      image: {
        id: "career-galatasaray",
        src: `${BASE}/kariyer-galatasaray.jpg`,
        alt: "Roland Sallai, Galatasaray formasıyla",
        placeholder: true,
        hint: "GS forması · şeridin en güçlü karesi · gol sevinci ya da kanatta hücum · yatay",
        width: 1200,
        height: 800,
      },
    },
  ],
  nights: [
    {
      year: 2017,
      title: "Lefkoşa'da Avrupa",
      meta: "Şampiyonlar Ligi grubu · APOEL",
      line: "Kıbrıs'taki küçük kulüp, kurada Real Madrid, Tottenham ve Dortmund ile aynı kutuya düştü. Yirmi yaşındaki bir kanat oyuncusu için Avrupa böyle açılır: bir gecede, hazır olmadan.",
      image: {
        id: "night-lefkosa",
        src: `${BASE}/gece-lefkosa.jpg`,
        alt: "",
        placeholder: true,
        hint: "APOEL forması · Şampiyonlar Ligi gecesi · projektör ışığı · yatay",
        width: 1200,
        height: 700,
      },
    },
    {
      year: 2021,
      title: "Dolu tribün",
      meta: "EURO 2020 · Macaristan — Fransa",
      line: "O yaz Avrupa'da kapasitesini tam dolduran tek stadyum Puskás Aréna'ydı. Dünya kapalıyken Budapeşte'de tribünler tıka basa doldu ve Macaristan sahadan beraberlikle çıktı.",
      image: {
        id: "night-puskas-arena",
        src: `${BASE}/gece-puskas-arena.jpg`,
        alt: "",
        placeholder: true,
        hint: "Macaristan millî forması · dolu tribün arkada görünsün · yatay",
        width: 1200,
        height: 700,
      },
    },
    {
      year: 2022,
      title: "Berlin'de final",
      meta: "Almanya Kupası finali · Freiburg — Leipzig",
      line: "Kulübün tarihindeki ilk kupa finali. Olympiastadion'da doksan dakika, uzatma ve penaltılar; kupa Leipzig'e gitti, ama o kadro Freiburg'un en uzağa gittiği kadro oldu.",
      image: {
        id: "night-berlin",
        src: `${BASE}/gece-berlin.jpg`,
        alt: "",
        placeholder: true,
        hint: "Olympiastadion · Freiburg forması · final atmosferi · yatay",
        width: 1200,
        height: 700,
      },
    },
    {
      year: 2022,
      title: "Molineux",
      meta: "Uluslar Ligi · İngiltere — Macaristan",
      line: "İngiltere kendi sahasında 4-0 yenildi ve gollerin ikisi Sallai'nindi. Macaristan için bir sonuçtan fazlasıydı; küçük bir ülkenin büyük bir ülkeye kendi evinde ders vermesiydi.",
      image: {
        id: "night-molineux",
        src: `${BASE}/gece-molineux.jpg`,
        alt: "",
        placeholder: true,
        hint: "Macaristan deplasman forması · gol sevinci · yatay",
        width: 1200,
        height: 700,
      },
    },
  ],
  personal: [
    {
      label: "Alışkanlık",
      title: "İlk temas ileri",
      body: "Topu kontrol ederken yana değil öne alır. Bu küçük tercih savunmacıyı yarım metre geri iter ve sonraki her şeyi kolaylaştırır. Kanat oyuncularının çoğu ilk temasla vakit kazanır; o ilk temasla mesafe kazanıyor.",
    },
    {
      label: "Mevki",
      title: "Nereye koyarsan",
      body: "Sağda başladı, solda oynadı, gerektiğinde forvet arkasına ve bek önüne çekildi. Teknik direktörlerin bu tip oyuncuyu sevmesinin sebebi golü değil, bir kadro sorununu tek başına kapatması. Çok yönlülüğün bedeli de var: her mevkide iyi olan, hiçbirinde vazgeçilmez sayılmıyor.",
    },
    {
      label: "Detay",
      title: "Geri koşu",
      body: "Topu kaybettiği anda durup söylenmiyor; ilk üç adımı hemen atıyor. Freiburg'da yedi yıl geçiren bir oyuncuda bu neredeyse bir refleks — o kulüp kanadına önce savunmayı öğretir. En çok bu koşuyu izliyorum, çünkü kimse alkışlamıyor.",
    },
  ],
  gallery: [
    {
      id: "gallery-1",
      src: `${BASE}/galeri-1.jpg`,
      alt: "Roland Sallai",
      placeholder: true,
      hint: "Ana galeri karesi · geniş · en yüksek çözünürlük · GS forması",
      width: 1600,
      height: 900,
      caption: "Ana kare",
    },
    {
      id: "gallery-2",
      src: `${BASE}/galeri-2.jpg`,
      alt: "Maç anı",
      placeholder: true,
      hint: "Maç anı · kanatta topla · yatay",
      width: 1200,
      height: 800,
      caption: "Maç anı",
    },
    {
      id: "gallery-3",
      src: `${BASE}/galeri-3.jpg`,
      alt: "Portre",
      placeholder: true,
      hint: "Portre · dikey · yüz net · sade zemin",
      width: 900,
      height: 1200,
      caption: "Portre",
    },
    {
      id: "gallery-4",
      src: `${BASE}/galeri-4.jpg`,
      alt: "Gol sevinci",
      placeholder: true,
      hint: "Gol sevinci · dikey · kollar açık",
      width: 900,
      height: 1200,
      caption: "Sevinç",
    },
    {
      id: "gallery-5",
      src: `${BASE}/galeri-5.jpg`,
      alt: "Millî forma",
      placeholder: true,
      hint: "Macaristan millî forması · yatay · millî marş ya da maç anı",
      width: 1200,
      height: 800,
      caption: "Millî forma",
    },
    {
      id: "gallery-6",
      src: `${BASE}/galeri-6.jpg`,
      alt: "Antrenman",
      placeholder: true,
      hint: "Antrenman · yatay ya da kare · sprint çalışması ideal",
      width: 1200,
      height: 800,
      caption: "Antrenman",
    },
    {
      id: "gallery-7",
      src: `${BASE}/galeri-7.jpg`,
      alt: "Tribün",
      placeholder: true,
      hint: "Taraftarla an · maç sonu tribüne selam · yatay",
      width: 1200,
      height: 800,
      caption: "Tribün",
    },
  ],

  /**
   * Sallai'nin imzası YÖN: hız, dikine oyun ve tekrar eden koşu. Bebas'ın
   * skorboard kondansesi, kadrajı yaran kinetik hero, arkada yay biçiminde
   * yörünge çizgileri; sıkışık ritim ve dokusuz zemin bu tempoyu bozmuyor.
   */
  design: {
    voice: "condensed",
    hero: "kinetic",
    signature: "arc",
    rhythm: "tight",
    texture: "clean",
  },
};
