import type { FavouritePlayer } from "./types";

/** Depodaki kareler bu klasörde bekliyor; küratörün yüklediği `/uploads/`de. */
const BASE = "/assets/players/sneijder";

/**
 * WESLEY SNEIJDER — Utrecht'ten çıkan on numara.
 *
 * ⚠️ SAYILAR DOĞRULANMADI — dış bir kaynakla karşılaştırılmadı.
 * Bu kayıtta bilerek AZ sayı var. Maç, gol ve asist toplamları yazılmadı;
 * kulüp kırılımındaki `matches` / `goals` alanları `null` bırakıldı. Yazılan
 * tek tek değerler (forma numarası, yıl aralıkları, şampiyonluk sayısı,
 * 2010 Dünya Kupası'ndaki gol sayısı) emin olunanlarla sınırlı. Küratör
 * düzeltmesi bu dosyada tek satır.
 *
 * ⚠️ RENK: mavi yok. Inter nötr taş tonuyla temsil ediliyor (`#6d6455`),
 * sayfanın ışığı Hollanda turuncusu + kemik + kömür üzerine kuruldu.
 */
export const wesleySneijder: FavouritePlayer = {
  slug: "sneijder",
  name: "Wesley Sneijder",
  firstName: "WESLEY",
  lastName: "SNEIJDER",
  shirt: 10,
  position: "Ofansif orta saha",
  club: "Galatasaray",
  clubShort: "GS",
  country: "Hollanda",
  countryCode: "NL",
  birthDate: "9 Haziran 1984",
  birthPlace: "Utrecht, Hollanda",
  height: "170 cm",
  weight: "—",
  tagline: "Topa dokunmadan önce oyunu bitirmiş olurdu.",
  quote: "Sahada en az koşan adamdı; topun en çok işine yarayan da oydu.",
  closingQuote:
    "Bir on numaranın işi topu ileri götürmek değil, oyunu bir saniye önce görmektir. O saniyeyi hep önden aldı.",
  palette: {
    ink: "#0f0a06",
    accent: "#f2892b",
    warm: "#e4d6b8",
    glow: "rgba(242, 137, 43, 0.30)",
    neon: "#b8531b",
  },
  hero: {
    id: "hero",
    src: `${BASE}/hero.jpg`,
    alt: "Wesley Sneijder, Galatasaray forması",
    placeholder: true,
    hint: "Dikey kadraj · GS forması · sakin yüz, top ayağında ya da pas anı · kalabalık arka plan bulanık",
    width: 1200,
    height: 1600,
  },
  card: {
    id: "card",
    src: `${BASE}/kart.jpg`,
    alt: "Wesley Sneijder",
    placeholder: true,
    hint: "Hub şeridindeki kart için · dikey · üst gövde · yüz net, göz teması olursa daha iyi",
    width: 900,
    height: 1200,
  },
  badges: ["On saha", "No. 10", "Galatasaray"],
  vitals: [
    { label: "Doğum tarihi", value: "09.06.1984" },
    { label: "Uyruk", value: "Hollanda" },
    { label: "Boy", value: "170 cm" },
    { label: "Forma", value: "10" },
  ],
  storyTitle: ["Topun", "önünü gören"],
  storyLede:
    "Utrecht'te doğdu, Amsterdam'da öğrendi, Madrid'de bekledi, Milano'da her şeyi tek bir yıla sığdırdı ve İstanbul'da dört buçuk sezon kaldı.",
  story: [
    "Utrecht'te bir futbol evinde büyüdü; kardeşleri de sahaya çıktı. Ajax'ın altyapısı onu çocukken aldı ve orada yalnızca ayağını değil, oyunu okumayı da çalıştırdı. Genç yaşta ilk takıma girdi, kısa süre sonra ligi kazandı. Boyu hakkında her zaman bir not düşüldü; ayağı hakkında hiç düşülmedi.",
    "2007'de Real Madrid'e gitti ve ilk sezonunda İspanya şampiyonu oldu. Ama Madrid, on numarasını uzun süre aynı yerde tutmayan bir kulüptür; ikinci yılın sonunda kapı sessizce kapandı. Çoğu oyuncu için bu bir düşüş olurdu.",
    "Milano bunu düşüş olarak okumadı. 2010, bir kariyere sığabilecek en yoğun yıllardan biriydi: Inter'le lig, kupa ve Şampiyonlar Ligi — İtalya'da bir takımın ilk üçlemesi. Yaz gelince Hollanda formasıyla Dünya Kupası finaline çıktı ve turnuvayı beş golle kapattı. O yılın büyük bireysel ödülü başkasına gitti ve bu, futbolun hâlâ tartışılan hesaplarından biri olarak kaldı.",
    "Ocak 2013'te İstanbul'a geldi. Dünya Kupası finali oynamış bir on numaranın Süper Lig'e gelmesi o gün için alışılmadıktı. Dört buçuk sezon kaldı, iki lig şampiyonluğu gördü ve kar altında yarım kalan bir Avrupa gecesinde takımı tur atlattı. Buradan sonrası kısa ve uzaktı: Fransa'da bir durak, Körfez'de bir mevsim, sonra sessizlik.",
  ],
  stats: {
    club: {
      key: "galatasaray",
      label: "Galatasaray",
      crest: {
        id: "crest-gs",
        src: `${BASE}/arma-gs.png`,
        alt: "Galatasaray arması",
        placeholder: true,
        hint: "Galatasaray arması · kare ya da dikey · zemini temiz, kenarlarda boşluk kalsın",
        width: 900,
        height: 900,
      },
      entries: [
        { key: "years", label: "Yıl", value: "2013 — 2017" },
        { key: "shirt", label: "Forma", value: "10" },
        { key: "titles", label: "Süper Lig", value: "2" },
      ],
      note: "Yarım sezonda gelip dört buçuk sezon kaldı; o süre boyunca on numara boşalmadı.",
    },
    all: {
      label: "Tüm zamanlar",
      entries: [
        { key: "leagues", label: "Şampiyon olduğu ülke", value: "4" },
        { key: "treble", label: "Üçleme", value: "2010" },
        { key: "worldcup", label: "Dünya Kupası", value: "2010 finali" },
        { key: "wcgoals", label: "2010'da gol", value: "5" },
      ],
      note: "Hollanda, İspanya, İtalya ve Türkiye — dört ayrı ülkede lig şampiyonluğu.",
    },
  },
  career: [
    {
      id: "ajax",
      years: "2002 — 2007",
      club: "Ajax",
      country: "Hollanda",
      note: "On numaranın ne iş yaptığını öğrendiği okul; ilk lig şampiyonluğu burada geldi.",
      tone: "#a8392c",
      matches: null,
      goals: null,
      image: {
        id: "career-ajax",
        src: `${BASE}/kariyer-ajax.jpg`,
        alt: "Wesley Sneijder, Ajax formasıyla",
        placeholder: true,
        hint: "Ajax forması · genç hâli · yatay · aksiyon ya da portre",
        width: 1200,
        height: 800,
      },
    },
    {
      id: "real-madrid",
      years: "2007 — 2009",
      club: "Real Madrid",
      country: "İspanya",
      note: "İlk sezonunda İspanya şampiyonluğu; ikinci yılın sonunda kapı sessizce kapandı.",
      tone: "#d9c9a8",
      matches: null,
      goals: null,
      image: {
        id: "career-real-madrid",
        src: `${BASE}/kariyer-real-madrid.jpg`,
        alt: "Wesley Sneijder, Real Madrid formasıyla",
        placeholder: true,
        hint: "Beyaz forma · yatay · tercihen Bernabéu ışığında",
        width: 1200,
        height: 800,
      },
    },
    {
      id: "inter",
      years: "2009 — 2013",
      club: "Inter",
      country: "İtalya",
      note: "Üçlemenin orta sahası; kariyerin tepe noktası tek bir yılın içine sığdı.",
      tone: "#6d6455",
      matches: null,
      goals: null,
      image: {
        id: "career-inter",
        src: `${BASE}/kariyer-inter.jpg`,
        alt: "Wesley Sneijder, Inter formasıyla",
        placeholder: true,
        hint: "Inter forması · yatay · MAVİYİ ÖNE ÇIKARMAYAN kare seç: gece ışığı, yakın plan, koyu kontrast",
        width: 1200,
        height: 800,
      },
    },
    {
      id: "galatasaray",
      years: "2013 — 2017",
      club: "Galatasaray",
      country: "Türkiye",
      note: "Dört buçuk sezon, iki şampiyonluk ve kar altında bir Avrupa gecesi.",
      tone: "#f2892b",
      matches: null,
      goals: null,
      current: true,
      image: {
        id: "career-galatasaray",
        src: `${BASE}/kariyer-galatasaray.jpg`,
        alt: "Wesley Sneijder, Galatasaray formasıyla",
        placeholder: true,
        hint: "GS forması · şeridin en güçlü karesi burası · gol sevinci ya da duran top başında",
        width: 1200,
        height: 800,
      },
    },
  ],
  nights: [
    {
      year: 2010,
      title: "Bernabéu'da üçleme",
      meta: "Şampiyonlar Ligi finali · Inter — Bayern München",
      line: "Bir yıl önce onu gönderen kulübün stadyumunda kupayı kaldırdı. Aynı sezon lig ve kupa da gelmişti; İtalya'da bir takım bunu ilk kez yapıyordu.",
      image: {
        id: "night-bernabeu",
        src: `${BASE}/gece-bernabeu.jpg`,
        alt: "Sneijder, 2010 Şampiyonlar Ligi finalinin ardından",
        placeholder: true,
        hint: "Kupa gecesi · yatay · konfeti ya da kupayla an · gece ışığı",
        width: 1200,
        height: 675,
      },
    },
    {
      year: 2010,
      title: "Port Elizabeth",
      meta: "Dünya Kupası çeyrek finali · Hollanda — Brezilya",
      line: "Brezilya öne geçti, sonra iki golün ikisi de onun hanesine yazıldı. Turnuvanın gidişatı o kırk beş dakikada döndü.",
      image: {
        id: "night-port-elizabeth",
        src: `${BASE}/gece-port-elizabeth.jpg`,
        alt: "Sneijder, Hollanda millî takımı formasıyla",
        placeholder: true,
        hint: "Turuncu millî forma · yatay · gol sevinci ya da kafa vuruşu anı",
        width: 1200,
        height: 675,
      },
    },
    {
      year: 2013,
      title: "Kar",
      meta: "Şampiyonlar Ligi · Galatasaray — Juventus",
      line: "Maç kar yüzünden ertesi güne kaldı. Yarım kalan oyunun devamında topu ağlara o gönderdi ve takım son on altıya kaldı.",
      image: {
        id: "night-kar",
        src: `${BASE}/gece-kar.jpg`,
        alt: "Kar altında oynanan Galatasaray — Juventus maçından bir kare",
        placeholder: true,
        hint: "Kar yağarken · GS forması · yatay · zeminde kar görünsün, arşivin en atmosferik karesi burası",
        width: 1200,
        height: 675,
      },
    },
    {
      year: 2015,
      title: "İkinci şampiyonluk",
      meta: "Süper Lig · 2014-15",
      line: "Lig ve kupa aynı sezonda geldi. İlk şampiyonluk yarım sezonda kucağına düşmüştü; bu, baştan sona onun sezonuydu.",
      image: {
        id: "night-sampiyonluk",
        src: `${BASE}/gece-sampiyonluk.jpg`,
        alt: "Sneijder, Galatasaray şampiyonluk kutlamasında",
        placeholder: true,
        hint: "Şampiyonluk kutlaması · GS forması · yatay · kupa ya da tribünle birlikte",
        width: 1200,
        height: 675,
      },
    },
  ],
  personal: [
    {
      label: "Duruş",
      title: "Top gelmeden dönmüş olurdu",
      body: "Pas ona ulaşmadan gövdesi çoktan yarım dönmüştü. Bu yüzden topu kontrol ettiği anda arkasını görmüş sayılırdı ve baskıya gelen rakip hep bir adım geç kalırdı. Herkes onun ayağına bakardı; iş aslında omuzlarında bitiyordu.",
    },
    {
      label: "Vuruş",
      title: "Geri salınım yok",
      body: "Uzaktan vururken bacağını geriye pek atmazdı; top ayağından neredeyse haber vermeden çıkardı. Kaleciyi yenen şey hızdan çok bu haber vermeyişti. Bir de son metrede topun aşağı düşmesi vardı — onun tarifi yok.",
    },
    {
      label: "Tempo",
      title: "Yürüyerek oynardı",
      body: "Doksan dakikanın çoğunu yürüyerek geçirirdi ve bu, tribünde her zaman hoş karşılanmadı. Sonra oyunun ortasında iki dokunuş yapar, maçın yönünü değiştirirdi. Koşu mesafesine bakan biri onu hiç anlamaz.",
    },
  ],
  gallery: [
    {
      id: "gallery-1",
      src: `${BASE}/galeri-1.jpg`,
      alt: "Wesley Sneijder, Galatasaray forması",
      placeholder: true,
      hint: "Ana galeri karesi · yatay · en yüksek çözünürlük · GS forması",
      width: 1600,
      height: 900,
      caption: "Ana kare",
    },
    {
      id: "gallery-2",
      src: `${BASE}/galeri-2.jpg`,
      alt: "Duran top başında",
      placeholder: true,
      hint: "Duran top başında · yandan · yatay · top yerde, gövde hafif yana yatık",
      width: 1200,
      height: 800,
      caption: "Duran top",
    },
    {
      id: "gallery-3",
      src: `${BASE}/galeri-3.jpg`,
      alt: "Portre",
      placeholder: true,
      hint: "Portre · dikey · yüz net · sakin ifade",
      width: 800,
      height: 1000,
      caption: "Portre",
    },
    {
      id: "gallery-4",
      src: `${BASE}/galeri-4.jpg`,
      alt: "Kar gecesinden bir kare",
      placeholder: true,
      hint: "Kar gecesi · Avrupa maçı · yatay · nefes buharı görünürse ideal",
      width: 1200,
      height: 720,
      caption: "Kar gecesi",
    },
    {
      id: "gallery-5",
      src: `${BASE}/galeri-5.jpg`,
      alt: "Hollanda millî takımı formasıyla",
      placeholder: true,
      hint: "Turuncu millî forma · dikey ya da kare · sayfanın rengini taşıyan kare bu",
      width: 900,
      height: 1100,
      caption: "Turuncu",
    },
    {
      id: "gallery-6",
      src: `${BASE}/galeri-6.jpg`,
      alt: "Kupa gecesi",
      placeholder: true,
      hint: "Kupa ya da şampiyonluk gecesi · yatay · kalabalık içinde",
      width: 1200,
      height: 800,
      caption: "Kupa",
    },
    {
      id: "gallery-7",
      src: `${BASE}/galeri-7.jpg`,
      alt: "Tribünle bir an",
      placeholder: true,
      hint: "Tribün ya da takım arkadaşlarıyla an · yatay · maç sonu",
      width: 1200,
      height: 800,
      caption: "Tribün",
    },
  ],

  /**
   * Sneijder'in imzası akışkan: editoryal serif, ortadan bölünmüş hero, dalga
   * motifi ve geniş sinematik nefes. Sayfa koşmuyor, yürüyor — oyuncunun
   * kendi temposu.
   */
  design: {
    voice: "editorial",
    hero: "split",
    signature: "wave",
    rhythm: "cinematic",
    texture: "halo",
    order: ["hikaye", "geceler", "kariyer", "istatistik", "anlar", "galeri"],
  },
};
