import type { FavouritePlayer } from "./types";

/** Kareler bu klasörde bekliyor; hepsi henüz boş — küratör yükleyecek. */
const BASE = "/assets/players/torreira";

/**
 * ⚠️ SAYILAR DOĞRULANMADI — dış bir kaynakla karşılaştırılmadı.
 * Küratör düzeltmesi bu dosyada tek satır.
 *
 * Bu kayıtta maç/gol/asist sayısı BİLEREK yazılmadı: emin olunmayan rakam
 * yerine satırın hiç konmaması tercih edildi (sözleşme §5). `career`
 * duraklarının `matches` ve `goals` alanları bu yüzden `null`.
 *
 * ⚠️ Uruguay'ın açık mavisi paletin dışında bırakıldı; burası bir Galatasaray
 * arşivi. Milli takım ve mavi formalı kulüpler nötr taş tonuyla temsil ediliyor.
 */
export const lucasTorreira: FavouritePlayer = {
  slug: "torreira",
  name: "Lucas Torreira",
  firstName: "LUCAS",
  lastName: "TORREIRA",
  shirt: 34,
  position: "Defansif orta saha",
  club: "Galatasaray",
  clubShort: "GS",
  country: "Uruguay",
  countryCode: "UY",
  birthDate: "11 Şubat 1996",
  birthPlace: "Fray Bentos, Uruguay",
  height: "168 cm",
  weight: "—",
  tagline: "Sahanın en küçük adamı, orta sahanın en geniş alanını kapatıyor.",
  quote: "Orta sahanın gürültüsünü de sessizliğini de aynı adam kuruyor.",
  closingQuote:
    "Büyük takımlar en çok, kimsenin alkışlamadığı işi her hafta yapan adamdan kurulur.",
  palette: {
    ink: "#0d0b0a",
    accent: "#c8552e",
    warm: "#a3937c",
    glow: "rgba(200, 85, 46, 0.28)",
    neon: "#5f2415",
  },
  hero: {
    id: "hero",
    src: `${BASE}/hero.jpg`,
    alt: "Lucas Torreira, Galatasaray forması",
    placeholder: true,
    hint: "Dikey kadraj · GS forması · ikili mücadele anı ya da sert bakışlı portre · yüz net",
    width: 1200,
    height: 1600,
  },
  card: {
    id: "card",
    src: `${BASE}/kart.jpg`,
    alt: "Lucas Torreira",
    placeholder: true,
    hint: "Hub şeridindeki kart için · dikey · üst gövde · sakin yüz",
    width: 900,
    height: 1200,
  },
  badges: ["Orta saha", "No. 34", "Galatasaray"],
  vitals: [
    { label: "Doğum tarihi", value: "11.02.1996" },
    { label: "Uyruk", value: "Uruguay" },
    { label: "Boy", value: "168 cm" },
    { label: "Mevki", value: "Ön libero" },
  ],
  storyTitle: ["Nehir kasabasından", "takımın motoruna"],
  storyLede:
    "Uruguay'ın küçük bir nehir kasabasından Serie B'ye, Londra'dan İstanbul'a: kulüpten kulübe taşıdığı tek şey, durduğu yerden geri çekilmemek.",
  story: [
    "Fray Bentos, Uruguay nehrinin kıyısında küçük bir kasaba. Adı futbolla değil, bir et fabrikasıyla anılır; oradan çıkıp Avrupa'ya varan çocuk sayısı azdır. Torreira önce Montevideo'ya, sonra çok genç yaşta İtalya'ya gitti.",
    "İtalya onu alt basamaktan karşıladı: Pescara, kimsenin izlemediği maçlar, dar sahalar. Serie B bir orta sahacıya iki şey öğretir — nerede duracağını ve fauli ne zaman göze alacağını. İkisini de orada öğrendi; Sampdoria'ya çıktığında hazırdı.",
    "2018'de Arsenal'e gitti. Emirates uzun süredir topu kesen birini bekliyordu ve onu ilk aydan benimsedi; kısa boylu, hep koşan, hiç yorulmayan biri geldiğinde tribün bunu hemen fark eder. Londra'daki son yılları kolay geçmedi, araya Madrid ve Floransa'da birer kiralık girdi.",
    "2022'de İstanbul'a kiralık geldi ve kaldı. Takım öne çıktığında arkada tek başına duran, geri düştüğünde ilk kavgayı başlatan adam oldu. Üst üste gelen şampiyonlukların hepsinde aynı yerde, aynı işi yaptı; o işin adı skor tablosunda görünmez.",
  ],
  stats: {
    club: {
      key: "galatasaray",
      label: "Galatasaray",
      crest: {
        id: "crest-gs",
        src: `${BASE}/arma-gs.png`,
        alt: "Galatasaray arması",
        placeholder: true,
        hint: "Galatasaray arması · kare ya da dikey · zemin temiz",
        width: 800,
        height: 800,
        credit: null,
      },
      entries: [
        { key: "since", label: "Geliş", value: "2022" },
        { key: "shirt", label: "Forma", value: "34" },
        { key: "titles", label: "Lig · 23 · 24 · 25", value: "3" },
      ],
      note: "Maç, gol ve asist sayıları doğrulanmadığı için buraya yazılmadı.",
    },
    all: {
      label: "Tüm zamanlar",
      entries: [
        { key: "clubs", label: "Avrupa'da kulüp", value: "6" },
        { key: "countries", label: "Oynadığı ülke", value: "4" },
        { key: "worldcups", label: "Dünya Kupası", value: "2" },
      ],
      note: "Pescara, Sampdoria, Arsenal, Atlético Madrid, Fiorentina ve Galatasaray; İtalya, İngiltere, İspanya, Türkiye. Toplam maç ve gol doğrulanmadığı için yazılmadı.",
    },
  },
  career: [
    {
      id: "sampdoria",
      years: "2016 — 2018",
      club: "Sampdoria",
      country: "İtalya",
      note: "Serie A'da adını duyurdu; İtalya ona durmayı, Genova ona sertliği öğretti.",
      tone: "#8d8778",
      matches: null,
      goals: null,
      image: {
        id: "career-sampdoria",
        src: `${BASE}/kariyer-sampdoria.jpg`,
        alt: "Torreira, Sampdoria formasıyla",
        placeholder: true,
        hint: "Sampdoria forması · yatay · aksiyon karesi · top kesme anı ideal",
        width: 1200,
        height: 800,
      },
    },
    {
      id: "arsenal",
      years: "2018 — 2022",
      club: "Arsenal",
      country: "İngiltere",
      note: "Emirates'in ilk aydan benimsediği oyuncu; araya Madrid'de bir sezonluk kiralık girdi.",
      tone: "#9c2b26",
      matches: null,
      goals: null,
      image: {
        id: "career-arsenal",
        src: `${BASE}/kariyer-arsenal.jpg`,
        alt: "Torreira, Arsenal formasıyla",
        placeholder: true,
        hint: "Arsenal forması · yatay · Emirates zemininde koşu ya da mücadele",
        width: 1200,
        height: 800,
      },
    },
    {
      id: "fiorentina",
      years: "2021 — 2022",
      club: "Fiorentina",
      country: "İtalya",
      note: "İtalya'ya dönüş; kendisini en rahat hissettiği ligde bir sezon.",
      tone: "#7c4450",
      matches: null,
      goals: null,
      image: {
        id: "career-fiorentina",
        src: `${BASE}/kariyer-fiorentina.jpg`,
        alt: "Torreira, Fiorentina formasıyla",
        placeholder: true,
        hint: "Fiorentina forması · yatay · sahada aksiyon",
        width: 1200,
        height: 800,
      },
    },
    {
      id: "galatasaray",
      years: "2022 —",
      club: "Galatasaray",
      country: "Türkiye",
      note: "Kiralık geldi, kaldı; takımın hızını ayarlayan adam oldu.",
      tone: "#c8552e",
      matches: null,
      goals: null,
      current: true,
      image: {
        id: "career-galatasaray",
        src: `${BASE}/kariyer-galatasaray.jpg`,
        alt: "Torreira, Galatasaray formasıyla",
        placeholder: true,
        hint: "GS forması · yatay · şeridin en güçlü karesi burası · tribün arkada görünsün",
        width: 1200,
        height: 800,
      },
    },
  ],
  nights: [
    {
      year: 2018,
      title: "İlk Dünya Kupası",
      meta: "Rusya 2018 · Uruguay",
      line: "Yirmi iki yaşında, Uruguay'ın orta sahasında. Oyunu kuranlar önündeydi; arkalarında kalan boşluğu tek başına kapatan oydu.",
      image: {
        id: "night-dunya-kupasi",
        src: `${BASE}/gece-dunya-kupasi.jpg`,
        alt: "",
        placeholder: true,
        hint: "Uruguay forması · yatay · milli takım maçı · mümkünse mücadele anı",
        width: 1200,
        height: 800,
      },
    },
    {
      year: 2018,
      title: "Kuzey Londra derbisi",
      meta: "Emirates · Arsenal — Tottenham",
      line: "Ceza sahasının kalabalığından çıkan top ona geldi ve ağlara gitti. O akşam tribün onun adını maç bittikten sonra da söylemeye devam etti.",
      image: {
        id: "night-derbi",
        src: `${BASE}/gece-derbi.jpg`,
        alt: "",
        placeholder: true,
        hint: "Arsenal forması · yatay · gol sevinci ya da tribüne koşu",
        width: 1200,
        height: 800,
      },
    },
    {
      year: 2023,
      title: "İlk şampiyonluk",
      meta: "Süper Lig · 2022-23 · Galatasaray",
      line: "İstanbul'daki ilk sezonun sonunda kupa. Kiralık gelen bir oyuncunun şampiyonluk gecesinde sahanın ortasında durması, kalmaya karar verdiğinin ilk işaretiydi.",
      image: {
        id: "night-ilk-sampiyonluk",
        src: `${BASE}/gece-ilk-sampiyonluk.jpg`,
        alt: "",
        placeholder: true,
        hint: "Şampiyonluk gecesi · yatay · konfeti · GS forması",
        width: 1200,
        height: 800,
      },
    },
    {
      year: 2025,
      title: "Ligin ve kupanın yılı",
      meta: "Süper Lig + Türkiye Kupası · Galatasaray",
      line: "İki kupanın aynı sezonda alındığı yıl. Sahanın en çok koşulan yerinde durdu; kupanın kaldırıldığı kare bunu göstermez.",
      image: {
        id: "night-cifte-kupa",
        src: `${BASE}/gece-cifte-kupa.jpg`,
        alt: "",
        placeholder: true,
        hint: "Kupa gecesi · yatay · kupayla birlikte ya da soyunma odası sevinci",
        width: 1200,
        height: 800,
      },
    },
  ],
  personal: [
    {
      label: "Alışkanlık",
      title: "Kesmez, yolu kapatır",
      body: "Topa gitmeden önce pasın nereye gideceğine karar verir ve o çizginin üstünde durur. En iyi müdahaleleri ayağının değdiği anlar değil, rakibin o pası hiç denemediği anlardır. Kalabalıkta bunu göremezsiniz; tekrar izlerken görürsünüz.",
    },
    {
      label: "Hareket",
      title: "İki dokunuş",
      body: "Topu kazandıktan sonra taşımaz. Bir dokunuşla kendine çevirir, ikincide en yakın açık oyuncuya bırakır ve hemen yeniden pozisyon alır. Kazanılan topu tutan orta sahacılar takımı yorar; o tersini yapıyor.",
    },
    {
      label: "Detay",
      title: "Alçak merkez",
      body: "İkili mücadelede kolunu değil kalçasını kullanır; boyu kısa olduğu için rakibin altına girer ve dengeyi oradan bozar. Kendinden uzun oyuncularla girdiği mücadelelerin çoğundan ayakta çıkması bu yüzden.",
    },
  ],
  gallery: [
    {
      id: "gallery-1",
      src: `${BASE}/galeri-1.jpg`,
      alt: "Lucas Torreira",
      placeholder: true,
      hint: "Ana galeri karesi · geniş · en yüksek çözünürlük · GS forması",
      width: 1280,
      height: 720,
      caption: "Ana kare",
    },
    {
      id: "gallery-2",
      src: `${BASE}/galeri-2.jpg`,
      alt: "Mücadele anı",
      placeholder: true,
      hint: "İkili mücadele · yatay · top ayakta, iki oyuncu kadrajda",
      width: 1200,
      height: 800,
      caption: "Mücadele",
    },
    {
      id: "gallery-3",
      src: `${BASE}/galeri-3.jpg`,
      alt: "Portre",
      placeholder: true,
      hint: "Portre · dikey · yakın plan · sakin yüz",
      width: 800,
      height: 1000,
      caption: "Portre",
    },
    {
      id: "gallery-4",
      src: `${BASE}/galeri-4.jpg`,
      alt: "Sevinç",
      placeholder: true,
      hint: "Gol ya da kupa sevinci · dikey · yüz net",
      width: 800,
      height: 1000,
      caption: "Sevinç",
    },
    {
      id: "gallery-5",
      src: `${BASE}/galeri-5.jpg`,
      alt: "Taraftarla an",
      placeholder: true,
      hint: "Tribün / taraftar · yatay · maç sonu selamı",
      width: 1200,
      height: 800,
      caption: "Tribün",
    },
    {
      id: "gallery-6",
      src: `${BASE}/galeri-6.jpg`,
      alt: "Antrenman",
      placeholder: true,
      hint: "Antrenman · yatay ya da kare · günlük ışık",
      width: 1000,
      height: 1000,
      caption: "Antrenman",
    },
    {
      id: "gallery-7",
      src: `${BASE}/galeri-7.jpg`,
      alt: "Kupa",
      placeholder: true,
      hint: "Kupa · şampiyonluk gecesi · dikey",
      width: 800,
      height: 1200,
      caption: "Kupa",
    },
  ],

  /**
   * FRAME + GRID + TIGHT: portre arşiv çerçevesinin içinde duruyor, arkada
   * teknik ızgara ve sıkışık dikey ritim — kompakt, yoğun bir blok. Sayfanın
   * iskeleti oyuncunun oynadığı alanla aynı: dar, düzenli, taşmayan.
   */
  design: {
    voice: "poster",
    hero: "frame",
    signature: "grid",
    rhythm: "tight",
    texture: "grain",
  },
};
