import type { RosterMember, TeamId } from "./types";

/**
 * SLAM DUNK EVRENİ — KADRO DEFTERİ (45 kayıt).
 *
 * ── KAYNAK VE DOĞRULAMA ──────────────────────────────────────────────────
 * Boy / kilo / numara / mevki / sınıf: `slamdunk.fandom.com` künye kutuları,
 * her kayıt tek tek okundu. Kanji adlar: ja.wikipedia
 * "SLAM DUNKの登場人物" — fandom künyelerinin yarısında kanji yok ve
 * tahmin yazmak yerine tek otoriter kaynaktan alındı.
 *
 * ⚠️ Bir çelişki bilerek çözüldü: Nagano’nun adı fandom’da 永野 充,
 * ja.wikipedia’da 永野 満. ja.wikipedia esas alındı.
 *
 * ⚠️ `null` UYDURMANIN ALTERNATİFİ. Shohoku’nun yedek sınıfında ve
 * Kainan’ın Kosuga’sında kaynakta boy/kilo YOK; arayüz o satırı
 * “kayıt yok” diye çiziyor (`slamDunk.roster.unknown`).
 *
 * ── STAT BARLARI CANON DEĞİL ─────────────────────────────────────────────
 * Slam Dunk hiçbir resmî kaynakta oyuncuları sayısal derecelendirmiyor.
 * Buradaki dört değer, künyelerin “Abilities / Strengths / Weakness”
 * bölümlerinden ve maç anlatılarından çıkarılmış ARŞİV DEĞERLENDİRMESİDİR.
 * Ölçek çapaları `types.ts` → `Stats` başlığında yazılı ve sayfa bunu
 * gizlemiyor: bar bloğunun altında kaynak notu basılıyor.
 *
 * ⚠️ Kimlikleri (`id`) DEĞİŞTİRME — küratörün yüklediği kare
 * `slam-dunk:player:<id>` yuvasına bağlı ve yeniden adlandırma o kareyi
 * koparır (`CuratedImage.slotId` sözleşmesi).
 */
export const ROSTER: RosterMember[] = [
  // ══════════════════════════════════════════════════════════════════
  // ŞOHOKU — 湘北高校
  // ══════════════════════════════════════════════════════════════════
  {
    id: "sakuragi",
    name: "Hanamichi Sakuragi",
    kanji: "桜木 花道",
    team: "shohoku",
    role: "player",
    number: 10,
    position: "PF",
    height: 189,
    weight: 83,
    year: 1,
    starter: true,
    epithet: { tr: "Ribaunt Kralı", en: "King of Rebounds" },
    note: {
      tr: "Dört ay önce topa ilk kez dokundu; bugün Kanagawa’nın en iyi ribaundcusu. Şutu hâlâ dar bir açıda güvenilir, gücü ve sıçraması sahada eşsiz.",
      en: "He touched a ball for the first time four months ago; today he is Kanagawa's best rebounder. His shot is reliable only from one narrow angle, but his power and leap have no equal on the floor.",
    },
    stats: { shooting: 52, defense: 62, rebounding: 97, speed: 88 },
  },
  {
    id: "rukawa",
    name: "Kaede Rukawa",
    kanji: "流川 楓",
    team: "shohoku",
    role: "player",
    number: 11,
    position: "SF",
    height: 187,
    weight: 75,
    year: 1,
    starter: true,
    epithet: { tr: "Süper Çaylak", en: "Super Rookie" },
    note: {
      tr: "Her mevkide oynayabilen çaylak. Gözü sakatlanınca serbest atışları gözleri kapalı attı; Anzai onu ve Sakuragi’yi eski öğrencisinden büyük iki yetenek sayıyor.",
      en: "A freshman who can play any position. With an injured eye he shot his free throws blind; Anzai rates him and Sakuragi above his own former protégé.",
    },
    stats: { shooting: 90, defense: 82, rebounding: 68, speed: 92 },
  },
  {
    id: "akagi",
    name: "Takenori Akagi",
    kanji: "赤木 剛憲",
    team: "shohoku",
    role: "player",
    number: 4,
    position: "C",
    height: 197,
    weight: 93,
    year: 3,
    starter: true,
    epithet: { tr: "Gori", en: "Gori" },
    note: {
      tr: "Takımın kaptanı ve pota altındaki duvarı. Bileği sakatken sahadan çıkmayı reddetti; ulusal şampiyonluk hayalini üç yıl boyunca tek başına taşıdı.",
      en: "Captain, and the wall beneath the rim. He refused to leave the floor on an injured ankle and carried the dream of a national title alone for three years.",
    },
    stats: { shooting: 72, defense: 90, rebounding: 90, speed: 58 },
  },
  {
    id: "miyagi",
    name: "Ryota Miyagi",
    kanji: "宮城 リョータ",
    team: "shohoku",
    role: "player",
    number: 7,
    position: "PG",
    height: 168,
    weight: 59,
    year: 2,
    starter: true,
    epithet: { tr: "Şimşek Ryota", en: "Lightning Flash Ryota" },
    note: {
      tr: "Serinin en hızlı oyuncusu. Boyu 168 olmasına rağmen Fujima ve Maki’ye ayak uyduruyor, çift markajı sığ dribbling’le kırıyor; Akagi’den sonra kaptanlığı devralıyor.",
      en: "The fastest player in the series. At 168 cm he still keeps pace with Fujima and Maki, breaks double teams with a shallow dribble, and takes the captaincy after Akagi.",
    },
    stats: { shooting: 55, defense: 82, rebounding: 42, speed: 97 },
  },
  {
    id: "mitsui",
    name: "Hisashi Mitsui",
    kanji: "三井 寿",
    team: "shohoku",
    role: "player",
    number: 14,
    position: "SG",
    height: 184,
    weight: 70,
    year: 3,
    starter: true,
    epithet: { tr: "Üç Sayının Efendisi", en: "The Three-Point Ace" },
    note: {
      tr: "Eski ortaokul MVP’si, iki yıllık aradan sonra dönen üç sayı uzmanı. Ayağı yere basınca kapanan savunma onu durdurmuyor; tek gerçek zaafı kondisyonu.",
      en: "A former junior-high MVP and a three-point specialist back after two lost years. Once his feet are set no closeout troubles him; his one real weakness is stamina.",
    },
    stats: { shooting: 95, defense: 78, rebounding: 48, speed: 62 },
  },
  {
    id: "kogure",
    name: "Kiminobu Kogure",
    kanji: "木暮 公延",
    team: "shohoku",
    role: "player",
    number: 5,
    position: "SF",
    height: 178,
    weight: 63,
    year: 3,
    epithet: { tr: "Güvenilir Yardımcı", en: "The Dependable Deputy" },
    note: {
      tr: "Kaptan yardımcısı ve takımın sessiz dengesi. Taoka’nın Ryonan maçını kaybetmesinin iki sebebinden biri: hafife alınan tecrübeli bir çok yönlü oyuncu.",
      en: "Vice-captain and the team's quiet balance. One of the two reasons Taoka lost the Ryonan game: an experienced all-rounder everyone underestimated.",
    },
    stats: { shooting: 68, defense: 60, rebounding: 52, speed: 48 },
  },
  {
    id: "yasuda",
    name: "Yasuharu Yasuda",
    kanji: "安田 靖春",
    team: "shohoku",
    role: "player",
    number: 6,
    position: "PG",
    height: 165,
    weight: 57,
    year: 2,
    epithet: null,
    note: {
      tr: "Miyagi’nin yedeği; küçük cüssesine rağmen topu kaybetmeyen, disiplinli bir kurucu.",
      en: "Miyagi's back-up; a disciplined point guard who protects the ball despite his small frame.",
    },
    stats: { shooting: 45, defense: 52, rebounding: 32, speed: 58 },
  },
  {
    id: "shiozaki",
    name: "Tetsushi Shiozaki",
    kanji: "潮崎 哲士",
    team: "shohoku",
    role: "player",
    number: 8,
    position: "SG",
    height: 170,
    weight: null,
    year: 2,
    epithet: null,
    note: {
      tr: "İkinci sınıf şutör gard; Mitsui dönmeden önceki kadroda ilk beşte oynadı.",
      en: "A second-year shooting guard who started before Mitsui returned to the squad.",
    },
    stats: { shooting: 44, defense: 46, rebounding: 34, speed: 54 },
  },
  {
    id: "kakuta",
    name: "Satoru Kakuta",
    kanji: "角田 悟",
    team: "shohoku",
    role: "player",
    number: 9,
    position: "PF",
    height: 180,
    weight: null,
    year: 2,
    epithet: null,
    note: {
      tr: "Pota altında güç forvet ya da pivot oynayan ikinci sınıf; Akagi çıktığında ilk çağrılan.",
      en: "A second-year who plays power forward or centre, and the first man called when Akagi leaves the floor.",
    },
    stats: { shooting: 40, defense: 50, rebounding: 52, speed: 40 },
  },
  {
    id: "iishi",
    name: "Kentaro Iishi",
    kanji: "石井 健太郎",
    team: "shohoku",
    role: "player",
    number: 12,
    position: "PG",
    height: 170,
    weight: null,
    year: 1,
    epithet: null,
    note: {
      tr: "Birinci sınıf gard. Kainan yenilgisinden sonraki üst sınıflar–çaylaklar maçında çaylak beşinde yer aldı.",
      en: "A freshman guard who lined up in the rookie five for the upperclassmen scrimmage after the Kainan defeat.",
    },
    stats: { shooting: 40, defense: 40, rebounding: 30, speed: 50 },
  },
  {
    id: "sasaoka",
    name: "Satoro Sasaoka",
    kanji: "佐々岡 智",
    team: "shohoku",
    role: "player",
    number: 13,
    position: "SG",
    height: 172,
    weight: null,
    year: 1,
    epithet: null,
    note: {
      tr: "Birinci sınıf şutör gard; resmî bir maçta henüz sahaya çıkmadı.",
      en: "A freshman shooting guard who has yet to appear in a competitive game.",
    },
    stats: { shooting: 40, defense: 38, rebounding: 32, speed: 48 },
  },
  {
    id: "kuwata",
    name: "Toki Kuwata",
    kanji: "桑田 登紀",
    team: "shohoku",
    role: "player",
    number: 15,
    position: "PG",
    height: 163,
    weight: null,
    year: 1,
    epithet: null,
    note: {
      tr: "Kadronun en kısa oyuncusu; birinci sınıf gard.",
      en: "The shortest player on the roster; a freshman guard.",
    },
    stats: { shooting: 38, defense: 38, rebounding: 28, speed: 52 },
  },
  {
    id: "anzai",
    name: "Mitsuyoshi Anzai",
    kanji: "安西 光義",
    team: "shohoku",
    role: "coach",
    number: null,
    position: null,
    height: null,
    weight: null,
    year: null,
    epithet: { tr: "Beyaz Saçlı Buda", en: "The White-Haired Buddha" },
    note: {
      tr: "Üniversitede “Beyaz Saçlı Şeytan” diye anılan sert antrenör; bugün oyuncularını kırmadan büyüten bir usta. Sakuragi’ye bir haftada yirmi bin şut attırdı.",
      en: "Once known at university as the White-Haired Devil, now a master who grows players without breaking them. He made Sakuragi take twenty thousand shots in a week.",
    },
    stats: null,
  },
  {
    id: "ayako",
    name: "Ayako",
    kanji: "彩子",
    team: "shohoku",
    role: "manager",
    number: null,
    position: null,
    height: null,
    weight: null,
    year: 2,
    epithet: null,
    note: {
      tr: "Takım menajeri. Basketbolu oyunculardan iyi biliyor, Miyagi’nin dizginlerini de elinde tutuyor.",
      en: "Team manager. She knows the game better than most of the players, and keeps Miyagi on a short leash.",
    },
    stats: null,
  },
  {
    id: "haruko",
    name: "Haruko Akagi",
    kanji: "赤木 晴子",
    team: "shohoku",
    role: "manager",
    number: null,
    position: null,
    height: null,
    weight: null,
    year: 1,
    epithet: null,
    note: {
      tr: "İkinci menajer ve Akagi’nin kız kardeşi. Sakuragi’yi basketbola çeken tek soruyu o sordu: “Basketbolu sever misin?”",
      en: "Second manager and Akagi's sister. She asked the one question that pulled Sakuragi into the game: do you like basketball?",
    },
    stats: null,
  },

  // ══════════════════════════════════════════════════════════════════
  // RYONAN — 陵南高校
  // ══════════════════════════════════════════════════════════════════
  {
    id: "uozumi",
    name: "Jun Uozumi",
    kanji: "魚住 純",
    team: "ryonan",
    role: "player",
    number: 4,
    position: "C",
    height: 202,
    weight: 90,
    year: 3,
    starter: true,
    epithet: { tr: "Ryonan’ın Kalesi", en: "Ryonan's Fortress" },
    note: {
      tr: "Serinin ikinci en uzun oyuncusu. Takezato maçında 35 sayı, 17 ribaunt, 4 blok; Akagi’yi bile zorlayan bir savunma varlığı.",
      en: "The second tallest player in the series. Thirty-five points, seventeen rebounds and four blocks against Takezato, and a defensive presence that troubles even Akagi.",
    },
    stats: { shooting: 60, defense: 88, rebounding: 88, speed: 45 },
  },
  {
    id: "sendoh",
    name: "Akira Sendoh",
    kanji: "仙道 彰",
    team: "ryonan",
    role: "player",
    number: 7,
    position: "SF",
    height: 190,
    weight: 79,
    year: 2,
    starter: true,
    epithet: { tr: "Skor Makinesi", en: "Scoring Machine" },
    note: {
      tr: "Çaylak yılında 47 sayı attı. İkinci yılında pas oyununu da açtı: hem kurucu hem bitirici olduğu için markajı imkânsız; oyunu koçundan iyi okuyor.",
      en: "Forty-seven points as a rookie. In his second year he opened up his passing too: impossible to guard because he is both creator and finisher, and he reads the game better than his own coach.",
    },
    stats: { shooting: 92, defense: 85, rebounding: 66, speed: 84 },
  },
  {
    id: "fukuda",
    name: "Kicchou Fukuda",
    kanji: "福田 吉兆",
    team: "ryonan",
    role: "player",
    number: 13,
    position: "PF",
    height: 188,
    weight: 80,
    year: 2,
    starter: true,
    epithet: { tr: "Pota Altının Yırtıcısı", en: "The Paint Predator" },
    note: {
      tr: "Bir kez sayı bulmaya başladığında durdurulamayan iç oyuncu. Karşılığı ağır: savunması o kadar zayıf ki Sakuragi bile önünden geçiyor.",
      en: "An inside scorer nobody stops once he gets going. The price is steep: his defence is so weak that even Sakuragi drives past him.",
    },
    stats: { shooting: 82, defense: 38, rebounding: 76, speed: 72 },
  },
  {
    id: "koshino",
    name: "Hiroaki Koshino",
    kanji: "越野 宏明",
    team: "ryonan",
    role: "player",
    number: 6,
    position: "SG",
    height: 174,
    weight: 62,
    year: 2,
    starter: true,
    epithet: null,
    note: {
      tr: "Sendoh’un ortaokuldan beri arkadaşı ve sahadaki dengeleyicisi; hırslı, çalışkan, sürekli konuşan bir gard.",
      en: "Sendoh's friend since junior high and his balance on the floor: a driven, hard-working guard who never stops talking.",
    },
    stats: { shooting: 66, defense: 62, rebounding: 40, speed: 74 },
  },
  {
    id: "uekusa",
    name: "Tomoyuki Uekusa",
    kanji: "植草 智之",
    team: "ryonan",
    role: "player",
    number: 8,
    position: "PG",
    height: 170,
    weight: 62,
    year: 2,
    starter: true,
    epithet: null,
    note: {
      tr: "Sendoh kurucuya geçtiğinde yerini alan sessiz oyun kurucu; Ryonan’ın en zayıf halkası olarak işaret edilen mevki.",
      en: "The quiet point guard who takes over when Sendoh moves to the one — the position the wiki itself marks as Ryonan's weakest link.",
    },
    stats: { shooting: 50, defense: 58, rebounding: 34, speed: 70 },
  },
  {
    id: "ikegami",
    name: "Ryoji Ikegami",
    kanji: "池上 亮二",
    team: "ryonan",
    role: "player",
    number: 5,
    position: "SF",
    height: 183,
    weight: 72,
    year: 3,
    epithet: null,
    note: {
      tr: "Kaptan yardımcısı ve Ryonan’ın en iyi üç savunmacısından biri; Mitsui’yi ayağı yere basmadan bastırarak durdurabilen ender oyunculardan.",
      en: "Vice-captain and one of Ryonan's three best defenders — one of the few who can stop Mitsui by pressuring him before his feet are set.",
    },
    stats: { shooting: 62, defense: 80, rebounding: 56, speed: 64 },
  },
  {
    id: "hikoichi",
    name: "Hikoichi Aida",
    kanji: "相田 彦一",
    team: "ryonan",
    role: "player",
    number: 15,
    position: "PG",
    height: 165,
    weight: 52,
    year: 1,
    epithet: { tr: "Not Defteri", en: "The Notebook" },
    note: {
      tr: "Oyuncu ve menajer. Rakiplerin her hareketini deftere yazıyor; Ryonan’ın istihbaratı onun elinden çıkıyor.",
      en: "Player and manager. He writes every opponent's move into a notebook — Ryonan's scouting comes out of his hands.",
    },
    stats: { shooting: 34, defense: 40, rebounding: 26, speed: 60 },
  },
  {
    id: "taoka",
    name: "Moichi Taoka",
    kanji: "田岡 茂一",
    team: "ryonan",
    role: "coach",
    number: null,
    position: null,
    height: null,
    weight: null,
    year: null,
    epithet: null,
    note: {
      tr: "Rakibin zayıf noktasını sökmekte usta, sert mizaçlı bir antrenör. Sendoh’u kurucu yapmayı ilk o düşündü; Sakuragi’yi hafife alarak finali kaybetti.",
      en: "A hard-nosed coach who is expert at picking apart an opponent's weak points. He was the first to see Sendoh as a point guard — and he lost the final by underestimating Sakuragi.",
    },
    stats: null,
  },

  // ══════════════════════════════════════════════════════════════════
  // KAINAN — 海南大附属高校
  // ══════════════════════════════════════════════════════════════════
  {
    id: "maki",
    name: "Shinichi Maki",
    kanji: "牧 紳一",
    team: "kainan",
    role: "player",
    number: 4,
    position: "PG",
    height: 184,
    weight: 79,
    year: 3,
    starter: true,
    epithet: { tr: "Kanagawa’nın Kralı", en: "King of Kanagawa" },
    note: {
      tr: "Beş mevkiyi de oynayabilen elit kurucu. Potaya gidişini kimse kesemiyor; hiçbir rakibi hafife almıyor, başka ile gidip rakip izliyor.",
      en: "An elite point guard who can play all five positions. Nobody cuts off his drive; he underestimates no opponent and travels to other prefectures to scout them.",
    },
    stats: { shooting: 80, defense: 88, rebounding: 60, speed: 90 },
  },
  {
    id: "jin",
    name: "Soichiro Jin",
    kanji: "神 宗一郎",
    team: "kainan",
    role: "player",
    number: 6,
    position: "SG",
    height: 189,
    weight: 71,
    year: 2,
    starter: true,
    epithet: { tr: "Keskin Nişancı", en: "The Marksman" },
    note: {
      tr: "Çizginin çok gerisinden rahatça atan üç sayıcı. Şut tehdidi savunmayı zıplatıyor; hafife alınan bir pas ustası da — ama yanal hızı zayıf.",
      en: "A three-point shooter comfortable well beyond the arc. The threat alone makes defenders jump; he is an underrated passer too — but his lateral quickness is a weakness.",
    },
    stats: { shooting: 96, defense: 62, rebounding: 44, speed: 58 },
  },
  {
    id: "kiyota",
    name: "Nobunaga Kiyota",
    kanji: "清田 信長",
    team: "kainan",
    role: "player",
    number: 10,
    /* ⚠️ Künye kutusu "Shooting Guard" yazıyor ama takım sayfası onu
       ilk beşin FORVETİ olarak sayıyor: "her iki forvet de 185 santimin
       altında" cümlesi Kiyota (178) ile Muto'yu (184) kastediyor ve Jin
       zaten şutör gard. Kaynak kendi içinde çelişiyor; dizilimi anlatan
       cümle esas alındı. */
    position: "SF",
    height: 178,
    weight: 65,
    year: 1,
    starter: true,
    epithet: { tr: "Vahşi Çocuk", en: "The Wild Boy" },
    note: {
      tr: "Kendini “süper çaylak” ilan eden atletik kanat. Rukawa’yı rakip, Sakuragi’yi baş belası biliyor; boy açığını sıçrayışıyla kapatıyor.",
      en: "An athletic wing who calls himself the super rookie. He treats Rukawa as his rival and Sakuragi as a nuisance, and covers his lack of height with his leap.",
    },
    stats: { shooting: 68, defense: 78, rebounding: 58, speed: 92 },
  },
  {
    id: "takasago",
    name: "Kazuma Takasago",
    kanji: "高砂 一馬",
    team: "kainan",
    role: "player",
    number: 5,
    position: "C",
    height: 191,
    weight: 80,
    year: 3,
    starter: true,
    epithet: null,
    note: {
      tr: "Kaptan yardımcısı pivot. Maki ve Jin savunmayı çektiği için pota altı ona kalıyor; Uozumi’yi faul limitine düşüren kurnazlık onun işi.",
      en: "The vice-captain centre. With Maki and Jin dragging defenders out, the paint belongs to him — and it was his cunning that fouled Uozumi out.",
    },
    stats: { shooting: 62, defense: 78, rebounding: 80, speed: 50 },
  },
  {
    id: "muto",
    name: "Tadashi Muto",
    kanji: "武藤 正",
    team: "kainan",
    role: "player",
    number: 9,
    position: "PF",
    height: 184,
    weight: 75,
    year: 3,
    starter: true,
    epithet: null,
    note: {
      tr: "Dribbling’den kendi sayısını üretebilen forvet ve Kainan’ın en iyi kilit savunmacılarından; zayıf takımlara karşı yıldız gibi oynuyor.",
      en: "A forward who creates his own offence off the dribble and one of Kainan's best lockdown defenders; against weaker teams he plays like a star.",
    },
    stats: { shooting: 74, defense: 76, rebounding: 62, speed: 66 },
  },
  {
    id: "kosuga",
    name: "Hiro Kosuga",
    kanji: "小菅",
    team: "kainan",
    role: "player",
    number: 8,
    position: "SG",
    height: null,
    weight: null,
    year: 2,
    epithet: null,
    note: {
      tr: "Dış çemberde duran, pota altına nadiren giren yedek gard.",
      en: "A reserve guard who stays on the perimeter and rarely ventures into the paint.",
    },
    stats: { shooting: 62, defense: 54, rebounding: 34, speed: 58 },
  },
  {
    id: "miyamasu",
    name: "Yoshinori Miyamasu",
    kanji: "宮益 義範",
    team: "kainan",
    role: "player",
    number: 15,
    position: "PG",
    height: 160,
    weight: 42,
    year: 3,
    epithet: { tr: "Uzaylı", en: "Space Alien" },
    note: {
      tr: "Kadronun en küçüğü ve yedek kulübesinin en güvenilir dış şut tehdidi; kimsenin beklemediği anda üçlük atıyor.",
      en: "The smallest man on the roster and the bench's most reliable outside threat, hitting threes exactly when nobody expects them.",
    },
    stats: { shooting: 72, defense: 44, rebounding: 24, speed: 56 },
  },
  {
    id: "takato",
    name: "Riki Takato",
    kanji: "高頭 力",
    team: "kainan",
    role: "coach",
    number: null,
    position: null,
    height: null,
    weight: null,
    year: null,
    epithet: null,
    note: {
      tr: "On yedi yıllık ulusal turnuva serisinin mimarı. “Zirvede duran sen, kazanmayı en çok isteyensin” sözü Maki’ye ait tarifi.",
      en: "The architect of a seventeen-year streak of national appearances, and the man who told Maki that the one standing at the top wants victory the most.",
    },
    stats: null,
  },

  // ══════════════════════════════════════════════════════════════════
  // SHOYO — 翔陽高校
  // ══════════════════════════════════════════════════════════════════
  {
    id: "fujima",
    name: "Kenji Fujima",
    kanji: "藤真 健司",
    team: "shoyo",
    role: "player",
    number: 4,
    position: "PG",
    height: 178,
    weight: 66,
    year: 3,
    starter: true,
    epithet: { tr: "Oyuncu-Koç", en: "Player-Coach" },
    note: {
      tr: "Hem kaptan hem antrenör. Kenarda soğukkanlı bir stratejist, sahaya girdiği anda maçın temposunu tek başına çeviren bir kurucu.",
      en: "Captain and coach at once: a cool strategist on the sideline, and a point guard who flips the tempo of a game the moment he steps on court.",
    },
    stats: { shooting: 84, defense: 76, rebounding: 44, speed: 88 },
  },
  {
    id: "hanagata",
    name: "Toru Hanagata",
    kanji: "花形 透",
    team: "shoyo",
    role: "player",
    number: 5,
    position: "C",
    height: 197,
    weight: 83,
    year: 3,
    starter: true,
    epithet: { tr: "Fadeaway", en: "The Fadeaway" },
    note: {
      tr: "Akagi ve Uozumi ayarında bir pivot; farkı gücü tekniğe karıştırması. Bloklanamayan fadeaway’i ve kanca şutu var, savunması hücumu kadar iyi değil.",
      en: "A centre on a par with Akagi and Uozumi, set apart by mixing power with technique. His fadeaway cannot be blocked and he has a hook shot; his defence does not match his offence.",
    },
    stats: { shooting: 80, defense: 66, rebounding: 82, speed: 60 },
  },
  {
    id: "hasegawa",
    name: "Kazushi Hasegawa",
    kanji: "長谷川 一志",
    team: "shoyo",
    role: "player",
    number: 6,
    position: "SG",
    height: 190,
    weight: 80,
    year: 3,
    starter: true,
    epithet: null,
    note: {
      tr: "190 santimlik şutör gard; Shoyo’nun boy üstünlüğünü dış çembere taşıyan oyuncu.",
      en: "A shooting guard of 190 cm who carries Shoyo's height advantage out to the perimeter.",
    },
    stats: { shooting: 66, defense: 60, rebounding: 60, speed: 58 },
  },
  {
    id: "nagano",
    name: "Mitsuru Nagano",
    kanji: "永野 満",
    team: "shoyo",
    role: "player",
    number: 7,
    /* ⚠️ Künye kutusu "Power Forward" diyor, takım tablosu yalnızca
       "Forward". Takano da (193 cm) uzun forvet ve ikisini aynı mevkiye
       yazmak beş kişilik dizilimi bozuyor; iki santim kısa olan Nagano
       kısa forvete alındı — takım tablosunun daha geniş etiketi buna
       izin veriyor. */
    position: "SF",
    height: 191,
    weight: 84,
    year: 3,
    starter: true,
    epithet: null,
    note: {
      tr: "Shoyo’nun uzun ilk beşinin bir parçası; pota altında Hanagata’nın yükünü paylaşan güç forvet.",
      en: "Part of Shoyo's oversized starting five: a power forward who shares Hanagata's load in the paint.",
    },
    stats: { shooting: 58, defense: 64, rebounding: 70, speed: 50 },
  },
  {
    id: "takano",
    name: "Shoichi Takano",
    kanji: "高野 昭一",
    team: "shoyo",
    role: "player",
    number: 8,
    position: "PF",
    height: 193,
    weight: 85,
    year: 3,
    starter: true,
    epithet: null,
    note: {
      tr: "İlk beşin en uzun ikinci ismi; Shoyo’nun ribaunt üstünlüğünü kuran son sınıf forveti.",
      en: "The second tallest starter, a senior forward who builds Shoyo's edge on the glass.",
    },
    stats: { shooting: 56, defense: 62, rebounding: 72, speed: 48 },
  },
  {
    id: "itou",
    name: "Taku Itou",
    kanji: "伊藤 卓",
    team: "shoyo",
    role: "player",
    number: 9,
    position: "PG",
    height: 180,
    weight: 71,
    year: 2,
    epithet: null,
    note: {
      tr: "Fujima kenarda kaldığı sürece sahadaki kurucu; kaptan girdiğinde yerini ona bırakıyor.",
      en: "The point guard on the floor for as long as Fujima stays on the bench, and the man who gives way when the captain checks in.",
    },
    stats: { shooting: 54, defense: 56, rebounding: 40, speed: 62 },
  },

  // ══════════════════════════════════════════════════════════════════
  // SANNOH — 山王工業高校
  // ══════════════════════════════════════════════════════════════════
  {
    id: "sawakita",
    name: "Eiji Sawakita",
    kanji: "沢北 栄治",
    team: "sannoh",
    role: "player",
    number: 9,
    position: "SF",
    height: 188,
    weight: 77,
    year: 2,
    starter: true,
    epithet: {
      tr: "Japonya’nın 1 Numaralı Lise Oyuncusu",
      en: "Japan's No. 1 High-School Player",
    },
    note: {
      tr: "Lisede — hatta üniversitede — birebirde onu yenebilecek kimse olmadığı söyleniyor. Hücumu neredeyse durdurulamaz, savunması hücumu kadar güçlü.",
      en: "It is said nobody in high school — or college — can beat him one on one. His offence is close to unstoppable and his defence matches it.",
    },
    stats: { shooting: 97, defense: 93, rebounding: 66, speed: 94 },
  },
  {
    id: "kawata-masashi",
    name: "Masashi Kawata",
    kanji: "河田 雅史",
    team: "sannoh",
    role: "player",
    number: 7,
    position: "C",
    height: 194,
    weight: 95,
    year: 3,
    starter: true,
    epithet: {
      tr: "Japonya’nın 1 Numaralı Pivotu",
      en: "Japan's No. 1 Centre",
    },
    note: {
      tr: "Çaylak yılında 165 santimdi, bir yılda 25 santim uzadı — o yüzden başka hiçbir pivotta olmayan gard becerileri var. Akagi’yi defalarca oyun dışı bıraktı.",
      en: "He was 165 cm as a freshman and grew twenty-five centimetres in a year, which is why he has guard skills no other centre owns. He isolated Akagi out of the game more than once.",
    },
    stats: { shooting: 84, defense: 94, rebounding: 94, speed: 74 },
  },
  {
    id: "fukatsu",
    name: "Kazunari Fukatsu",
    kanji: "深津 一成",
    team: "sannoh",
    role: "player",
    number: 4,
    position: "PG",
    height: 180,
    weight: null,
    year: 3,
    starter: true,
    epithet: { tr: "Buz Gibi Kaptan", en: "The Ice-Cold Captain" },
    note: {
      tr: "Pas, üç sayı ve savunmayı aynı anda taşıyan çok yönlü kurucu. Hiçbir şey karşısında etkilenmiyor; rakip momentum yakaladım sandığı anda vuruyor.",
      en: "An all-round point guard carrying passing, three-point shooting and defence at once. Nothing impresses him, and he strikes exactly when the opponent thinks the momentum is theirs.",
    },
    stats: { shooting: 82, defense: 88, rebounding: 46, speed: 82 },
  },
  {
    id: "nobe",
    name: "Masahiro Nobe",
    kanji: "野辺 将広",
    team: "sannoh",
    role: "player",
    number: 5,
    position: "PF",
    height: 198,
    weight: 90,
    year: 3,
    starter: true,
    epithet: { tr: "Totem Direği", en: "Totem Pole" },
    note: {
      tr: "Kaptan yardımcısı ve Sannoh’un pota altındaki uzunluğu; ribaunt ve blokta ülkenin en iyileriyle aynı sınıfta.",
      en: "Vice-captain and Sannoh's length in the paint, in the same class as the country's best on the glass and at the rim.",
    },
    stats: { shooting: 52, defense: 86, rebounding: 88, speed: 56 },
  },
  {
    id: "matsumoto",
    name: "Minoru Matsumoto",
    kanji: "松本 稔",
    team: "sannoh",
    role: "player",
    number: 6,
    position: "SG",
    height: 185,
    weight: 76,
    year: 3,
    starter: true,
    epithet: { tr: "Sırık", en: "Beanpole" },
    note: {
      tr: "Üç sayı çizgisini geren şutör gard; Sannoh’un tam saha baskısında dış çemberi kapatan isim.",
      en: "A shooting guard who stretches the arc, and the man who closes the perimeter in Sannoh's full-court press.",
    },
    stats: { shooting: 84, defense: 70, rebounding: 48, speed: 64 },
  },
  {
    id: "ichinokura",
    name: "Satoshi Ichinokura",
    kanji: "一之倉 聡",
    team: "sannoh",
    role: "player",
    number: 8,
    position: "SG",
    height: 171,
    weight: null,
    year: 3,
    epithet: { tr: "Kıskaç", en: "The Clamp" },
    note: {
      tr: "Savunma uzmanı. Mitsui’yi topu almadan bastırarak susturan iki oyuncudan biri; yedek kulübesinden gelip maçın yönünü değiştiriyor.",
      en: "A defensive specialist and one of only two players who silence Mitsui by pressuring him before he even receives the ball — off the bench, and the game turns.",
    },
    stats: { shooting: 48, defense: 92, rebounding: 34, speed: 80 },
  },
  {
    id: "kawata-mikio",
    name: "Mikio Kawata",
    kanji: "河田 美紀男",
    team: "sannoh",
    role: "player",
    number: 15,
    position: "C",
    height: 210,
    weight: 130,
    year: 1,
    epithet: { tr: "Dev", en: "The Giant" },
    note: {
      tr: "Serinin en uzun ve en ağır oyuncusu; Masashi’nin küçük kardeşi. Acemi ama cüssesi tek başına Sakuragi’yi ribauntdan uzak tutuyor.",
      en: "The tallest and heaviest player in the series and Masashi's younger brother. He is a beginner, but his sheer bulk alone keeps Sakuragi off the glass.",
    },
    stats: { shooting: 34, defense: 74, rebounding: 84, speed: 26 },
  },
  {
    id: "domoto",
    name: "Goro Domoto",
    kanji: "堂本 五郎",
    team: "sannoh",
    role: "coach",
    number: null,
    position: null,
    height: null,
    weight: null,
    year: null,
    epithet: null,
    note: {
      tr: "Üç yıllık şampiyonluğun antrenörü. En zayıf rakibi bile gece boyunca analiz ettiriyor, maç öncesi üniversite takımlarıyla prova yaptırıyor.",
      en: "The coach behind three straight titles. He has even the weakest opponent analysed all night, and scrimmages his team against college sides before the game.",
    },
    stats: null,
  },
];

/** Kimlik → kayıt. Yuva manifestosu ve bölümler bunu okuyor. */
export const ROSTER_BY_ID: Record<string, RosterMember> = Object.fromEntries(
  ROSTER.map((member) => [member.id, member]),
);

/** Takımın kadrosu — forma numarasına göre, numarasızlar (koç/menajer) sonda. */
export function teamRoster(team: TeamId): RosterMember[] {
  return ROSTER.filter((member) => member.team === team).sort((a, b) => {
    if (a.number === null && b.number === null) return 0;
    if (a.number === null) return 1;
    if (b.number === null) return -1;
    return a.number - b.number;
  });
}

/** Takımın sahneye çıkan beşi — kart sırası kadro sırasıyla aynı değil, mevkiye göre. */
const STARTER_ORDER = ["PG", "SG", "SF", "PF", "C"] as const;

export function teamStarters(team: TeamId): RosterMember[] {
  return ROSTER.filter(
    (member) => member.team === team && member.starter,
  ).sort(
    (a, b) =>
      STARTER_ORDER.indexOf(a.position as (typeof STARTER_ORDER)[number]) -
      STARTER_ORDER.indexOf(b.position as (typeof STARTER_ORDER)[number]),
  );
}

/** Takımın oyuncu olmayan kayıtları — koç, menajer. */
export function teamStaff(team: TeamId): RosterMember[] {
  return ROSTER.filter(
    (member) => member.team === team && member.role !== "player",
  );
}
